// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/v1/ebpf_services.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnableSockmapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodNamespace  string                 `protobuf:"bytes,1,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableSockmapRequest) Reset() {
	*x = EnableSockmapRequest{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableSockmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableSockmapRequest) ProtoMessage() {}

func (x *EnableSockmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableSockmapRequest.ProtoReflect.Descriptor instead.
func (*EnableSockmapRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{0}
}

func (x *EnableSockmapRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *EnableSockmapRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

type EnableSockmapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableSockmapResponse) Reset() {
	*x = EnableSockmapResponse{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableSockmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableSockmapResponse) ProtoMessage() {}

func (x *EnableSockmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableSockmapResponse.ProtoReflect.Descriptor instead.
func (*EnableSockmapResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{1}
}

type DisableSockmapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodNamespace  string                 `protobuf:"bytes,1,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableSockmapRequest) Reset() {
	*x = DisableSockmapRequest{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableSockmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableSockmapRequest) ProtoMessage() {}

func (x *DisableSockmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableSockmapRequest.ProtoReflect.Descriptor instead.
func (*DisableSockmapRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{2}
}

func (x *DisableSockmapRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *DisableSockmapRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

type DisableSockmapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableSockmapResponse) Reset() {
	*x = DisableSockmapResponse{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableSockmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableSockmapResponse) ProtoMessage() {}

func (x *DisableSockmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableSockmapResponse.ProtoReflect.Descriptor instead.
func (*DisableSockmapResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{3}
}

type GetSockmapStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSockmapStatsRequest) Reset() {
	*x = GetSockmapStatsRequest{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSockmapStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSockmapStatsRequest) ProtoMessage() {}

func (x *GetSockmapStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSockmapStatsRequest.ProtoReflect.Descriptor instead.
func (*GetSockmapStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{4}
}

type GetSockmapStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redirected    uint64                 `protobuf:"varint,1,opt,name=redirected,proto3" json:"redirected,omitempty"`
	Fallback      uint64                 `protobuf:"varint,2,opt,name=fallback,proto3" json:"fallback,omitempty"`
	ActiveSockets uint32                 `protobuf:"varint,3,opt,name=active_sockets,json=activeSockets,proto3" json:"active_sockets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSockmapStatsResponse) Reset() {
	*x = GetSockmapStatsResponse{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSockmapStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSockmapStatsResponse) ProtoMessage() {}

func (x *GetSockmapStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSockmapStatsResponse.ProtoReflect.Descriptor instead.
func (*GetSockmapStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{5}
}

func (x *GetSockmapStatsResponse) GetRedirected() uint64 {
	if x != nil {
		return x.Redirected
	}
	return 0
}

func (x *GetSockmapStatsResponse) GetFallback() uint64 {
	if x != nil {
		return x.Fallback
	}
	return 0
}

func (x *GetSockmapStatsResponse) GetActiveSockets() uint32 {
	if x != nil {
		return x.ActiveSockets
	}
	return 0
}

type AddMeshRedirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	RedirectPort  uint32                 `protobuf:"varint,3,opt,name=redirect_port,json=redirectPort,proto3" json:"redirect_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMeshRedirectRequest) Reset() {
	*x = AddMeshRedirectRequest{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMeshRedirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMeshRedirectRequest) ProtoMessage() {}

func (x *AddMeshRedirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMeshRedirectRequest.ProtoReflect.Descriptor instead.
func (*AddMeshRedirectRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{6}
}

func (x *AddMeshRedirectRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AddMeshRedirectRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AddMeshRedirectRequest) GetRedirectPort() uint32 {
	if x != nil {
		return x.RedirectPort
	}
	return 0
}

type AddMeshRedirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMeshRedirectResponse) Reset() {
	*x = AddMeshRedirectResponse{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMeshRedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMeshRedirectResponse) ProtoMessage() {}

func (x *AddMeshRedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMeshRedirectResponse.ProtoReflect.Descriptor instead.
func (*AddMeshRedirectResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{7}
}

type RemoveMeshRedirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMeshRedirectRequest) Reset() {
	*x = RemoveMeshRedirectRequest{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMeshRedirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMeshRedirectRequest) ProtoMessage() {}

func (x *RemoveMeshRedirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMeshRedirectRequest.ProtoReflect.Descriptor instead.
func (*RemoveMeshRedirectRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveMeshRedirectRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RemoveMeshRedirectRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RemoveMeshRedirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMeshRedirectResponse) Reset() {
	*x = RemoveMeshRedirectResponse{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMeshRedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMeshRedirectResponse) ProtoMessage() {}

func (x *RemoveMeshRedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMeshRedirectResponse.ProtoReflect.Descriptor instead.
func (*RemoveMeshRedirectResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{9}
}

type ListMeshRedirectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeshRedirectsRequest) Reset() {
	*x = ListMeshRedirectsRequest{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeshRedirectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeshRedirectsRequest) ProtoMessage() {}

func (x *ListMeshRedirectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeshRedirectsRequest.ProtoReflect.Descriptor instead.
func (*ListMeshRedirectsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{10}
}

type ListMeshRedirectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MeshRedirectEntry   `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeshRedirectsResponse) Reset() {
	*x = ListMeshRedirectsResponse{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeshRedirectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeshRedirectsResponse) ProtoMessage() {}

func (x *ListMeshRedirectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeshRedirectsResponse.ProtoReflect.Descriptor instead.
func (*ListMeshRedirectsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{11}
}

func (x *ListMeshRedirectsResponse) GetEntries() []*MeshRedirectEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MeshRedirectEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	RedirectPort  uint32                 `protobuf:"varint,3,opt,name=redirect_port,json=redirectPort,proto3" json:"redirect_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshRedirectEntry) Reset() {
	*x = MeshRedirectEntry{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshRedirectEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshRedirectEntry) ProtoMessage() {}

func (x *MeshRedirectEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshRedirectEntry.ProtoReflect.Descriptor instead.
func (*MeshRedirectEntry) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{12}
}

func (x *MeshRedirectEntry) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *MeshRedirectEntry) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MeshRedirectEntry) GetRedirectPort() uint32 {
	if x != nil {
		return x.RedirectPort
	}
	return 0
}

type ConfigureRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Rate          uint32                 `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Burst         uint32                 `protobuf:"varint,3,opt,name=burst,proto3" json:"burst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRateLimitRequest) Reset() {
	*x = ConfigureRateLimitRequest{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRateLimitRequest) ProtoMessage() {}

func (x *ConfigureRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRateLimitRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigureRateLimitRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *ConfigureRateLimitRequest) GetRate() uint32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ConfigureRateLimitRequest) GetBurst() uint32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

type ConfigureRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRateLimitResponse) Reset() {
	*x = ConfigureRateLimitResponse{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRateLimitResponse) ProtoMessage() {}

func (x *ConfigureRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRateLimitResponse.ProtoReflect.Descriptor instead.
func (*ConfigureRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{14}
}

type RemoveRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRateLimitRequest) Reset() {
	*x = RemoveRateLimitRequest{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRateLimitRequest) ProtoMessage() {}

func (x *RemoveRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRateLimitRequest.ProtoReflect.Descriptor instead.
func (*RemoveRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveRateLimitRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type RemoveRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRateLimitResponse) Reset() {
	*x = RemoveRateLimitResponse{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRateLimitResponse) ProtoMessage() {}

func (x *RemoveRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRateLimitResponse.ProtoReflect.Descriptor instead.
func (*RemoveRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{16}
}

type GetRateLimitStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateLimitStatsRequest) Reset() {
	*x = GetRateLimitStatsRequest{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateLimitStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateLimitStatsRequest) ProtoMessage() {}

func (x *GetRateLimitStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateLimitStatsRequest.ProtoReflect.Descriptor instead.
func (*GetRateLimitStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{17}
}

func (x *GetRateLimitStatsRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type GetRateLimitStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       uint64                 `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Denied        uint64                 `protobuf:"varint,2,opt,name=denied,proto3" json:"denied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateLimitStatsResponse) Reset() {
	*x = GetRateLimitStatsResponse{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateLimitStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateLimitStatsResponse) ProtoMessage() {}

func (x *GetRateLimitStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateLimitStatsResponse.ProtoReflect.Descriptor instead.
func (*GetRateLimitStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{18}
}

func (x *GetRateLimitStatsResponse) GetAllowed() uint64 {
	if x != nil {
		return x.Allowed
	}
	return 0
}

func (x *GetRateLimitStatsResponse) GetDenied() uint64 {
	if x != nil {
		return x.Denied
	}
	return 0
}

type GetBackendHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackendHealthRequest) Reset() {
	*x = GetBackendHealthRequest{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackendHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackendHealthRequest) ProtoMessage() {}

func (x *GetBackendHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackendHealthRequest.ProtoReflect.Descriptor instead.
func (*GetBackendHealthRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{19}
}

func (x *GetBackendHealthRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GetBackendHealthRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type GetBackendHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backends      []*BackendHealthInfo   `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackendHealthResponse) Reset() {
	*x = GetBackendHealthResponse{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackendHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackendHealthResponse) ProtoMessage() {}

func (x *GetBackendHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackendHealthResponse.ProtoReflect.Descriptor instead.
func (*GetBackendHealthResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{20}
}

func (x *GetBackendHealthResponse) GetBackends() []*BackendHealthInfo {
	if x != nil {
		return x.Backends
	}
	return nil
}

type BackendHealthInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	TotalConns    uint64                 `protobuf:"varint,3,opt,name=total_conns,json=totalConns,proto3" json:"total_conns,omitempty"`
	FailedConns   uint64                 `protobuf:"varint,4,opt,name=failed_conns,json=failedConns,proto3" json:"failed_conns,omitempty"`
	TimeoutConns  uint64                 `protobuf:"varint,5,opt,name=timeout_conns,json=timeoutConns,proto3" json:"timeout_conns,omitempty"`
	SuccessConns  uint64                 `protobuf:"varint,6,opt,name=success_conns,json=successConns,proto3" json:"success_conns,omitempty"`
	AvgRttNs      uint64                 `protobuf:"varint,7,opt,name=avg_rtt_ns,json=avgRttNs,proto3" json:"avg_rtt_ns,omitempty"`
	FailureRate   float64                `protobuf:"fixed64,8,opt,name=failure_rate,json=failureRate,proto3" json:"failure_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendHealthInfo) Reset() {
	*x = BackendHealthInfo{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendHealthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendHealthInfo) ProtoMessage() {}

func (x *BackendHealthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendHealthInfo.ProtoReflect.Descriptor instead.
func (*BackendHealthInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{21}
}

func (x *BackendHealthInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BackendHealthInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *BackendHealthInfo) GetTotalConns() uint64 {
	if x != nil {
		return x.TotalConns
	}
	return 0
}

func (x *BackendHealthInfo) GetFailedConns() uint64 {
	if x != nil {
		return x.FailedConns
	}
	return 0
}

func (x *BackendHealthInfo) GetTimeoutConns() uint64 {
	if x != nil {
		return x.TimeoutConns
	}
	return 0
}

func (x *BackendHealthInfo) GetSuccessConns() uint64 {
	if x != nil {
		return x.SuccessConns
	}
	return 0
}

func (x *BackendHealthInfo) GetAvgRttNs() uint64 {
	if x != nil {
		return x.AvgRttNs
	}
	return 0
}

func (x *BackendHealthInfo) GetFailureRate() float64 {
	if x != nil {
		return x.FailureRate
	}
	return 0
}

type StreamBackendHealthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PollIntervalMs uint32                 `protobuf:"varint,1,opt,name=poll_interval_ms,json=pollIntervalMs,proto3" json:"poll_interval_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamBackendHealthRequest) Reset() {
	*x = StreamBackendHealthRequest{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBackendHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBackendHealthRequest) ProtoMessage() {}

func (x *StreamBackendHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBackendHealthRequest.ProtoReflect.Descriptor instead.
func (*StreamBackendHealthRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{22}
}

func (x *StreamBackendHealthRequest) GetPollIntervalMs() uint32 {
	if x != nil {
		return x.PollIntervalMs
	}
	return 0
}

type BackendHealthEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backend       *BackendHealthInfo     `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	TimestampNs   uint64                 `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendHealthEvent) Reset() {
	*x = BackendHealthEvent{}
	mi := &file_api_v1_ebpf_services_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendHealthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendHealthEvent) ProtoMessage() {}

func (x *BackendHealthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ebpf_services_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendHealthEvent.ProtoReflect.Descriptor instead.
func (*BackendHealthEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_ebpf_services_proto_rawDescGZIP(), []int{23}
}

func (x *BackendHealthEvent) GetBackend() *BackendHealthInfo {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *BackendHealthEvent) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

var File_api_v1_ebpf_services_proto protoreflect.FileDescriptor

const file_api_v1_ebpf_services_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/v1/ebpf_services.proto\x12\n" +
	"novanet.v1\"V\n" +
	"\x14EnableSockmapRequest\x12#\n" +
	"\rpod_namespace\x18\x01 \x01(\tR\fpodNamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\"\x17\n" +
	"\x15EnableSockmapResponse\"W\n" +
	"\x15DisableSockmapRequest\x12#\n" +
	"\rpod_namespace\x18\x01 \x01(\tR\fpodNamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\"\x18\n" +
	"\x16DisableSockmapResponse\"\x18\n" +
	"\x16GetSockmapStatsRequest\"|\n" +
	"\x17GetSockmapStatsResponse\x12\x1e\n" +
	"\n" +
	"redirected\x18\x01 \x01(\x04R\n" +
	"redirected\x12\x1a\n" +
	"\bfallback\x18\x02 \x01(\x04R\bfallback\x12%\n" +
	"\x0eactive_sockets\x18\x03 \x01(\rR\ractiveSockets\"a\n" +
	"\x16AddMeshRedirectRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12#\n" +
	"\rredirect_port\x18\x03 \x01(\rR\fredirectPort\"\x19\n" +
	"\x17AddMeshRedirectResponse\"?\n" +
	"\x19RemoveMeshRedirectRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\x1c\n" +
	"\x1aRemoveMeshRedirectResponse\"\x1a\n" +
	"\x18ListMeshRedirectsRequest\"T\n" +
	"\x19ListMeshRedirectsResponse\x127\n" +
	"\aentries\x18\x01 \x03(\v2\x1d.novanet.v1.MeshRedirectEntryR\aentries\"\\\n" +
	"\x11MeshRedirectEntry\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12#\n" +
	"\rredirect_port\x18\x03 \x01(\rR\fredirectPort\"Y\n" +
	"\x19ConfigureRateLimitRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\rR\x04rate\x12\x14\n" +
	"\x05burst\x18\x03 \x01(\rR\x05burst\"\x1c\n" +
	"\x1aConfigureRateLimitResponse\",\n" +
	"\x16RemoveRateLimitRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\"\x19\n" +
	"\x17RemoveRateLimitResponse\".\n" +
	"\x18GetRateLimitStatsRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\"M\n" +
	"\x19GetRateLimitStatsResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\x04R\aallowed\x12\x16\n" +
	"\x06denied\x18\x02 \x01(\x04R\x06denied\"=\n" +
	"\x17GetBackendHealthRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"U\n" +
	"\x18GetBackendHealthResponse\x129\n" +
	"\bbackends\x18\x01 \x03(\v2\x1d.novanet.v1.BackendHealthInfoR\bbackends\"\x86\x02\n" +
	"\x11BackendHealthInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1f\n" +
	"\vtotal_conns\x18\x03 \x01(\x04R\n" +
	"totalConns\x12!\n" +
	"\ffailed_conns\x18\x04 \x01(\x04R\vfailedConns\x12#\n" +
	"\rtimeout_conns\x18\x05 \x01(\x04R\ftimeoutConns\x12#\n" +
	"\rsuccess_conns\x18\x06 \x01(\x04R\fsuccessConns\x12\x1c\n" +
	"\n" +
	"avg_rtt_ns\x18\a \x01(\x04R\bavgRttNs\x12!\n" +
	"\ffailure_rate\x18\b \x01(\x01R\vfailureRate\"F\n" +
	"\x1aStreamBackendHealthRequest\x12(\n" +
	"\x10poll_interval_ms\x18\x01 \x01(\rR\x0epollIntervalMs\"p\n" +
	"\x12BackendHealthEvent\x127\n" +
	"\abackend\x18\x01 \x01(\v2\x1d.novanet.v1.BackendHealthInfoR\abackend\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x04R\vtimestampNs2\x9f\b\n" +
	"\fEBPFServices\x12T\n" +
	"\rEnableSockmap\x12 .novanet.v1.EnableSockmapRequest\x1a!.novanet.v1.EnableSockmapResponse\x12W\n" +
	"\x0eDisableSockmap\x12!.novanet.v1.DisableSockmapRequest\x1a\".novanet.v1.DisableSockmapResponse\x12Z\n" +
	"\x0fGetSockmapStats\x12\".novanet.v1.GetSockmapStatsRequest\x1a#.novanet.v1.GetSockmapStatsResponse\x12Z\n" +
	"\x0fAddMeshRedirect\x12\".novanet.v1.AddMeshRedirectRequest\x1a#.novanet.v1.AddMeshRedirectResponse\x12c\n" +
	"\x12RemoveMeshRedirect\x12%.novanet.v1.RemoveMeshRedirectRequest\x1a&.novanet.v1.RemoveMeshRedirectResponse\x12`\n" +
	"\x11ListMeshRedirects\x12$.novanet.v1.ListMeshRedirectsRequest\x1a%.novanet.v1.ListMeshRedirectsResponse\x12c\n" +
	"\x12ConfigureRateLimit\x12%.novanet.v1.ConfigureRateLimitRequest\x1a&.novanet.v1.ConfigureRateLimitResponse\x12Z\n" +
	"\x0fRemoveRateLimit\x12\".novanet.v1.RemoveRateLimitRequest\x1a#.novanet.v1.RemoveRateLimitResponse\x12`\n" +
	"\x11GetRateLimitStats\x12$.novanet.v1.GetRateLimitStatsRequest\x1a%.novanet.v1.GetRateLimitStatsResponse\x12]\n" +
	"\x10GetBackendHealth\x12#.novanet.v1.GetBackendHealthRequest\x1a$.novanet.v1.GetBackendHealthResponse\x12_\n" +
	"\x13StreamBackendHealth\x12&.novanet.v1.StreamBackendHealthRequest\x1a\x1e.novanet.v1.BackendHealthEvent0\x01B$Z\"github.com/azrtydxb/novanet/api/v1b\x06proto3"

var (
	file_api_v1_ebpf_services_proto_rawDescOnce sync.Once
	file_api_v1_ebpf_services_proto_rawDescData []byte
)

func file_api_v1_ebpf_services_proto_rawDescGZIP() []byte {
	file_api_v1_ebpf_services_proto_rawDescOnce.Do(func() {
		file_api_v1_ebpf_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_ebpf_services_proto_rawDesc), len(file_api_v1_ebpf_services_proto_rawDesc)))
	})
	return file_api_v1_ebpf_services_proto_rawDescData
}

var file_api_v1_ebpf_services_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_v1_ebpf_services_proto_goTypes = []any{
	(*EnableSockmapRequest)(nil),       // 0: novanet.v1.EnableSockmapRequest
	(*EnableSockmapResponse)(nil),      // 1: novanet.v1.EnableSockmapResponse
	(*DisableSockmapRequest)(nil),      // 2: novanet.v1.DisableSockmapRequest
	(*DisableSockmapResponse)(nil),     // 3: novanet.v1.DisableSockmapResponse
	(*GetSockmapStatsRequest)(nil),     // 4: novanet.v1.GetSockmapStatsRequest
	(*GetSockmapStatsResponse)(nil),    // 5: novanet.v1.GetSockmapStatsResponse
	(*AddMeshRedirectRequest)(nil),     // 6: novanet.v1.AddMeshRedirectRequest
	(*AddMeshRedirectResponse)(nil),    // 7: novanet.v1.AddMeshRedirectResponse
	(*RemoveMeshRedirectRequest)(nil),  // 8: novanet.v1.RemoveMeshRedirectRequest
	(*RemoveMeshRedirectResponse)(nil), // 9: novanet.v1.RemoveMeshRedirectResponse
	(*ListMeshRedirectsRequest)(nil),   // 10: novanet.v1.ListMeshRedirectsRequest
	(*ListMeshRedirectsResponse)(nil),  // 11: novanet.v1.ListMeshRedirectsResponse
	(*MeshRedirectEntry)(nil),          // 12: novanet.v1.MeshRedirectEntry
	(*ConfigureRateLimitRequest)(nil),  // 13: novanet.v1.ConfigureRateLimitRequest
	(*ConfigureRateLimitResponse)(nil), // 14: novanet.v1.ConfigureRateLimitResponse
	(*RemoveRateLimitRequest)(nil),     // 15: novanet.v1.RemoveRateLimitRequest
	(*RemoveRateLimitResponse)(nil),    // 16: novanet.v1.RemoveRateLimitResponse
	(*GetRateLimitStatsRequest)(nil),   // 17: novanet.v1.GetRateLimitStatsRequest
	(*GetRateLimitStatsResponse)(nil),  // 18: novanet.v1.GetRateLimitStatsResponse
	(*GetBackendHealthRequest)(nil),    // 19: novanet.v1.GetBackendHealthRequest
	(*GetBackendHealthResponse)(nil),   // 20: novanet.v1.GetBackendHealthResponse
	(*BackendHealthInfo)(nil),          // 21: novanet.v1.BackendHealthInfo
	(*StreamBackendHealthRequest)(nil), // 22: novanet.v1.StreamBackendHealthRequest
	(*BackendHealthEvent)(nil),         // 23: novanet.v1.BackendHealthEvent
}
var file_api_v1_ebpf_services_proto_depIdxs = []int32{
	12, // 0: novanet.v1.ListMeshRedirectsResponse.entries:type_name -> novanet.v1.MeshRedirectEntry
	21, // 1: novanet.v1.GetBackendHealthResponse.backends:type_name -> novanet.v1.BackendHealthInfo
	21, // 2: novanet.v1.BackendHealthEvent.backend:type_name -> novanet.v1.BackendHealthInfo
	0,  // 3: novanet.v1.EBPFServices.EnableSockmap:input_type -> novanet.v1.EnableSockmapRequest
	2,  // 4: novanet.v1.EBPFServices.DisableSockmap:input_type -> novanet.v1.DisableSockmapRequest
	4,  // 5: novanet.v1.EBPFServices.GetSockmapStats:input_type -> novanet.v1.GetSockmapStatsRequest
	6,  // 6: novanet.v1.EBPFServices.AddMeshRedirect:input_type -> novanet.v1.AddMeshRedirectRequest
	8,  // 7: novanet.v1.EBPFServices.RemoveMeshRedirect:input_type -> novanet.v1.RemoveMeshRedirectRequest
	10, // 8: novanet.v1.EBPFServices.ListMeshRedirects:input_type -> novanet.v1.ListMeshRedirectsRequest
	13, // 9: novanet.v1.EBPFServices.ConfigureRateLimit:input_type -> novanet.v1.ConfigureRateLimitRequest
	15, // 10: novanet.v1.EBPFServices.RemoveRateLimit:input_type -> novanet.v1.RemoveRateLimitRequest
	17, // 11: novanet.v1.EBPFServices.GetRateLimitStats:input_type -> novanet.v1.GetRateLimitStatsRequest
	19, // 12: novanet.v1.EBPFServices.GetBackendHealth:input_type -> novanet.v1.GetBackendHealthRequest
	22, // 13: novanet.v1.EBPFServices.StreamBackendHealth:input_type -> novanet.v1.StreamBackendHealthRequest
	1,  // 14: novanet.v1.EBPFServices.EnableSockmap:output_type -> novanet.v1.EnableSockmapResponse
	3,  // 15: novanet.v1.EBPFServices.DisableSockmap:output_type -> novanet.v1.DisableSockmapResponse
	5,  // 16: novanet.v1.EBPFServices.GetSockmapStats:output_type -> novanet.v1.GetSockmapStatsResponse
	7,  // 17: novanet.v1.EBPFServices.AddMeshRedirect:output_type -> novanet.v1.AddMeshRedirectResponse
	9,  // 18: novanet.v1.EBPFServices.RemoveMeshRedirect:output_type -> novanet.v1.RemoveMeshRedirectResponse
	11, // 19: novanet.v1.EBPFServices.ListMeshRedirects:output_type -> novanet.v1.ListMeshRedirectsResponse
	14, // 20: novanet.v1.EBPFServices.ConfigureRateLimit:output_type -> novanet.v1.ConfigureRateLimitResponse
	16, // 21: novanet.v1.EBPFServices.RemoveRateLimit:output_type -> novanet.v1.RemoveRateLimitResponse
	18, // 22: novanet.v1.EBPFServices.GetRateLimitStats:output_type -> novanet.v1.GetRateLimitStatsResponse
	20, // 23: novanet.v1.EBPFServices.GetBackendHealth:output_type -> novanet.v1.GetBackendHealthResponse
	23, // 24: novanet.v1.EBPFServices.StreamBackendHealth:output_type -> novanet.v1.BackendHealthEvent
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_ebpf_services_proto_init() }
func file_api_v1_ebpf_services_proto_init() {
	if File_api_v1_ebpf_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_ebpf_services_proto_rawDesc), len(file_api_v1_ebpf_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_ebpf_services_proto_goTypes,
		DependencyIndexes: file_api_v1_ebpf_services_proto_depIdxs,
		MessageInfos:      file_api_v1_ebpf_services_proto_msgTypes,
	}.Build()
	File_api_v1_ebpf_services_proto = out.File
	file_api_v1_ebpf_services_proto_goTypes = nil
	file_api_v1_ebpf_services_proto_depIdxs = nil
}
