// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/v1/ebpf_services.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EBPFServices_EnableSockmap_FullMethodName       = "/novanet.v1.EBPFServices/EnableSockmap"
	EBPFServices_DisableSockmap_FullMethodName      = "/novanet.v1.EBPFServices/DisableSockmap"
	EBPFServices_GetSockmapStats_FullMethodName     = "/novanet.v1.EBPFServices/GetSockmapStats"
	EBPFServices_AddMeshRedirect_FullMethodName     = "/novanet.v1.EBPFServices/AddMeshRedirect"
	EBPFServices_RemoveMeshRedirect_FullMethodName  = "/novanet.v1.EBPFServices/RemoveMeshRedirect"
	EBPFServices_ListMeshRedirects_FullMethodName   = "/novanet.v1.EBPFServices/ListMeshRedirects"
	EBPFServices_ConfigureRateLimit_FullMethodName  = "/novanet.v1.EBPFServices/ConfigureRateLimit"
	EBPFServices_RemoveRateLimit_FullMethodName     = "/novanet.v1.EBPFServices/RemoveRateLimit"
	EBPFServices_GetRateLimitStats_FullMethodName   = "/novanet.v1.EBPFServices/GetRateLimitStats"
	EBPFServices_GetBackendHealth_FullMethodName    = "/novanet.v1.EBPFServices/GetBackendHealth"
	EBPFServices_StreamBackendHealth_FullMethodName = "/novanet.v1.EBPFServices/StreamBackendHealth"
)

// EBPFServicesClient is the client API for EBPFServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EBPFServices is the API that external consumers (e.g. NovaEdge) call
// to request kernel-level eBPF operations from the NovaNet agent.
type EBPFServicesClient interface {
	// SOCKMAP - same-node pod-to-pod acceleration
	EnableSockmap(ctx context.Context, in *EnableSockmapRequest, opts ...grpc.CallOption) (*EnableSockmapResponse, error)
	DisableSockmap(ctx context.Context, in *DisableSockmapRequest, opts ...grpc.CallOption) (*DisableSockmapResponse, error)
	GetSockmapStats(ctx context.Context, in *GetSockmapStatsRequest, opts ...grpc.CallOption) (*GetSockmapStatsResponse, error)
	// SK_LOOKUP - mesh traffic redirection
	AddMeshRedirect(ctx context.Context, in *AddMeshRedirectRequest, opts ...grpc.CallOption) (*AddMeshRedirectResponse, error)
	RemoveMeshRedirect(ctx context.Context, in *RemoveMeshRedirectRequest, opts ...grpc.CallOption) (*RemoveMeshRedirectResponse, error)
	ListMeshRedirects(ctx context.Context, in *ListMeshRedirectsRequest, opts ...grpc.CallOption) (*ListMeshRedirectsResponse, error)
	// Rate limiting - kernel-level per-source-IP
	ConfigureRateLimit(ctx context.Context, in *ConfigureRateLimitRequest, opts ...grpc.CallOption) (*ConfigureRateLimitResponse, error)
	RemoveRateLimit(ctx context.Context, in *RemoveRateLimitRequest, opts ...grpc.CallOption) (*RemoveRateLimitResponse, error)
	GetRateLimitStats(ctx context.Context, in *GetRateLimitStatsRequest, opts ...grpc.CallOption) (*GetRateLimitStatsResponse, error)
	// Health monitoring - passive TCP counters
	GetBackendHealth(ctx context.Context, in *GetBackendHealthRequest, opts ...grpc.CallOption) (*GetBackendHealthResponse, error)
	StreamBackendHealth(ctx context.Context, in *StreamBackendHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackendHealthEvent], error)
}

type eBPFServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewEBPFServicesClient(cc grpc.ClientConnInterface) EBPFServicesClient {
	return &eBPFServicesClient{cc}
}

func (c *eBPFServicesClient) EnableSockmap(ctx context.Context, in *EnableSockmapRequest, opts ...grpc.CallOption) (*EnableSockmapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableSockmapResponse)
	err := c.cc.Invoke(ctx, EBPFServices_EnableSockmap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eBPFServicesClient) DisableSockmap(ctx context.Context, in *DisableSockmapRequest, opts ...grpc.CallOption) (*DisableSockmapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableSockmapResponse)
	err := c.cc.Invoke(ctx, EBPFServices_DisableSockmap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eBPFServicesClient) GetSockmapStats(ctx context.Context, in *GetSockmapStatsRequest, opts ...grpc.CallOption) (*GetSockmapStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSockmapStatsResponse)
	err := c.cc.Invoke(ctx, EBPFServices_GetSockmapStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eBPFServicesClient) AddMeshRedirect(ctx context.Context, in *AddMeshRedirectRequest, opts ...grpc.CallOption) (*AddMeshRedirectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMeshRedirectResponse)
	err := c.cc.Invoke(ctx, EBPFServices_AddMeshRedirect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eBPFServicesClient) RemoveMeshRedirect(ctx context.Context, in *RemoveMeshRedirectRequest, opts ...grpc.CallOption) (*RemoveMeshRedirectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMeshRedirectResponse)
	err := c.cc.Invoke(ctx, EBPFServices_RemoveMeshRedirect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eBPFServicesClient) ListMeshRedirects(ctx context.Context, in *ListMeshRedirectsRequest, opts ...grpc.CallOption) (*ListMeshRedirectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMeshRedirectsResponse)
	err := c.cc.Invoke(ctx, EBPFServices_ListMeshRedirects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eBPFServicesClient) ConfigureRateLimit(ctx context.Context, in *ConfigureRateLimitRequest, opts ...grpc.CallOption) (*ConfigureRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureRateLimitResponse)
	err := c.cc.Invoke(ctx, EBPFServices_ConfigureRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eBPFServicesClient) RemoveRateLimit(ctx context.Context, in *RemoveRateLimitRequest, opts ...grpc.CallOption) (*RemoveRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRateLimitResponse)
	err := c.cc.Invoke(ctx, EBPFServices_RemoveRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eBPFServicesClient) GetRateLimitStats(ctx context.Context, in *GetRateLimitStatsRequest, opts ...grpc.CallOption) (*GetRateLimitStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRateLimitStatsResponse)
	err := c.cc.Invoke(ctx, EBPFServices_GetRateLimitStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eBPFServicesClient) GetBackendHealth(ctx context.Context, in *GetBackendHealthRequest, opts ...grpc.CallOption) (*GetBackendHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBackendHealthResponse)
	err := c.cc.Invoke(ctx, EBPFServices_GetBackendHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eBPFServicesClient) StreamBackendHealth(ctx context.Context, in *StreamBackendHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackendHealthEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EBPFServices_ServiceDesc.Streams[0], EBPFServices_StreamBackendHealth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBackendHealthRequest, BackendHealthEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EBPFServices_StreamBackendHealthClient = grpc.ServerStreamingClient[BackendHealthEvent]

// EBPFServicesServer is the server API for EBPFServices service.
// All implementations must embed UnimplementedEBPFServicesServer
// for forward compatibility.
//
// EBPFServices is the API that external consumers (e.g. NovaEdge) call
// to request kernel-level eBPF operations from the NovaNet agent.
type EBPFServicesServer interface {
	// SOCKMAP - same-node pod-to-pod acceleration
	EnableSockmap(context.Context, *EnableSockmapRequest) (*EnableSockmapResponse, error)
	DisableSockmap(context.Context, *DisableSockmapRequest) (*DisableSockmapResponse, error)
	GetSockmapStats(context.Context, *GetSockmapStatsRequest) (*GetSockmapStatsResponse, error)
	// SK_LOOKUP - mesh traffic redirection
	AddMeshRedirect(context.Context, *AddMeshRedirectRequest) (*AddMeshRedirectResponse, error)
	RemoveMeshRedirect(context.Context, *RemoveMeshRedirectRequest) (*RemoveMeshRedirectResponse, error)
	ListMeshRedirects(context.Context, *ListMeshRedirectsRequest) (*ListMeshRedirectsResponse, error)
	// Rate limiting - kernel-level per-source-IP
	ConfigureRateLimit(context.Context, *ConfigureRateLimitRequest) (*ConfigureRateLimitResponse, error)
	RemoveRateLimit(context.Context, *RemoveRateLimitRequest) (*RemoveRateLimitResponse, error)
	GetRateLimitStats(context.Context, *GetRateLimitStatsRequest) (*GetRateLimitStatsResponse, error)
	// Health monitoring - passive TCP counters
	GetBackendHealth(context.Context, *GetBackendHealthRequest) (*GetBackendHealthResponse, error)
	StreamBackendHealth(*StreamBackendHealthRequest, grpc.ServerStreamingServer[BackendHealthEvent]) error
	mustEmbedUnimplementedEBPFServicesServer()
}

// UnimplementedEBPFServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEBPFServicesServer struct{}

func (UnimplementedEBPFServicesServer) EnableSockmap(context.Context, *EnableSockmapRequest) (*EnableSockmapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableSockmap not implemented")
}
func (UnimplementedEBPFServicesServer) DisableSockmap(context.Context, *DisableSockmapRequest) (*DisableSockmapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableSockmap not implemented")
}
func (UnimplementedEBPFServicesServer) GetSockmapStats(context.Context, *GetSockmapStatsRequest) (*GetSockmapStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSockmapStats not implemented")
}
func (UnimplementedEBPFServicesServer) AddMeshRedirect(context.Context, *AddMeshRedirectRequest) (*AddMeshRedirectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMeshRedirect not implemented")
}
func (UnimplementedEBPFServicesServer) RemoveMeshRedirect(context.Context, *RemoveMeshRedirectRequest) (*RemoveMeshRedirectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMeshRedirect not implemented")
}
func (UnimplementedEBPFServicesServer) ListMeshRedirects(context.Context, *ListMeshRedirectsRequest) (*ListMeshRedirectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMeshRedirects not implemented")
}
func (UnimplementedEBPFServicesServer) ConfigureRateLimit(context.Context, *ConfigureRateLimitRequest) (*ConfigureRateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureRateLimit not implemented")
}
func (UnimplementedEBPFServicesServer) RemoveRateLimit(context.Context, *RemoveRateLimitRequest) (*RemoveRateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRateLimit not implemented")
}
func (UnimplementedEBPFServicesServer) GetRateLimitStats(context.Context, *GetRateLimitStatsRequest) (*GetRateLimitStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRateLimitStats not implemented")
}
func (UnimplementedEBPFServicesServer) GetBackendHealth(context.Context, *GetBackendHealthRequest) (*GetBackendHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBackendHealth not implemented")
}
func (UnimplementedEBPFServicesServer) StreamBackendHealth(*StreamBackendHealthRequest, grpc.ServerStreamingServer[BackendHealthEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamBackendHealth not implemented")
}
func (UnimplementedEBPFServicesServer) mustEmbedUnimplementedEBPFServicesServer() {}
func (UnimplementedEBPFServicesServer) testEmbeddedByValue()                      {}

// UnsafeEBPFServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EBPFServicesServer will
// result in compilation errors.
type UnsafeEBPFServicesServer interface {
	mustEmbedUnimplementedEBPFServicesServer()
}

func RegisterEBPFServicesServer(s grpc.ServiceRegistrar, srv EBPFServicesServer) {
	// If the following call panics, it indicates UnimplementedEBPFServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EBPFServices_ServiceDesc, srv)
}

func _EBPFServices_EnableSockmap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableSockmapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EBPFServicesServer).EnableSockmap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EBPFServices_EnableSockmap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EBPFServicesServer).EnableSockmap(ctx, req.(*EnableSockmapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EBPFServices_DisableSockmap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableSockmapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EBPFServicesServer).DisableSockmap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EBPFServices_DisableSockmap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EBPFServicesServer).DisableSockmap(ctx, req.(*DisableSockmapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EBPFServices_GetSockmapStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSockmapStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EBPFServicesServer).GetSockmapStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EBPFServices_GetSockmapStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EBPFServicesServer).GetSockmapStats(ctx, req.(*GetSockmapStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EBPFServices_AddMeshRedirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMeshRedirectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EBPFServicesServer).AddMeshRedirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EBPFServices_AddMeshRedirect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EBPFServicesServer).AddMeshRedirect(ctx, req.(*AddMeshRedirectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EBPFServices_RemoveMeshRedirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMeshRedirectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EBPFServicesServer).RemoveMeshRedirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EBPFServices_RemoveMeshRedirect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EBPFServicesServer).RemoveMeshRedirect(ctx, req.(*RemoveMeshRedirectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EBPFServices_ListMeshRedirects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMeshRedirectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EBPFServicesServer).ListMeshRedirects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EBPFServices_ListMeshRedirects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EBPFServicesServer).ListMeshRedirects(ctx, req.(*ListMeshRedirectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EBPFServices_ConfigureRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EBPFServicesServer).ConfigureRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EBPFServices_ConfigureRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EBPFServicesServer).ConfigureRateLimit(ctx, req.(*ConfigureRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EBPFServices_RemoveRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EBPFServicesServer).RemoveRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EBPFServices_RemoveRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EBPFServicesServer).RemoveRateLimit(ctx, req.(*RemoveRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EBPFServices_GetRateLimitStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRateLimitStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EBPFServicesServer).GetRateLimitStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EBPFServices_GetRateLimitStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EBPFServicesServer).GetRateLimitStats(ctx, req.(*GetRateLimitStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EBPFServices_GetBackendHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackendHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EBPFServicesServer).GetBackendHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EBPFServices_GetBackendHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EBPFServicesServer).GetBackendHealth(ctx, req.(*GetBackendHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EBPFServices_StreamBackendHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBackendHealthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EBPFServicesServer).StreamBackendHealth(m, &grpc.GenericServerStream[StreamBackendHealthRequest, BackendHealthEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EBPFServices_StreamBackendHealthServer = grpc.ServerStreamingServer[BackendHealthEvent]

// EBPFServices_ServiceDesc is the grpc.ServiceDesc for EBPFServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EBPFServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novanet.v1.EBPFServices",
	HandlerType: (*EBPFServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnableSockmap",
			Handler:    _EBPFServices_EnableSockmap_Handler,
		},
		{
			MethodName: "DisableSockmap",
			Handler:    _EBPFServices_DisableSockmap_Handler,
		},
		{
			MethodName: "GetSockmapStats",
			Handler:    _EBPFServices_GetSockmapStats_Handler,
		},
		{
			MethodName: "AddMeshRedirect",
			Handler:    _EBPFServices_AddMeshRedirect_Handler,
		},
		{
			MethodName: "RemoveMeshRedirect",
			Handler:    _EBPFServices_RemoveMeshRedirect_Handler,
		},
		{
			MethodName: "ListMeshRedirects",
			Handler:    _EBPFServices_ListMeshRedirects_Handler,
		},
		{
			MethodName: "ConfigureRateLimit",
			Handler:    _EBPFServices_ConfigureRateLimit_Handler,
		},
		{
			MethodName: "RemoveRateLimit",
			Handler:    _EBPFServices_RemoveRateLimit_Handler,
		},
		{
			MethodName: "GetRateLimitStats",
			Handler:    _EBPFServices_GetRateLimitStats_Handler,
		},
		{
			MethodName: "GetBackendHealth",
			Handler:    _EBPFServices_GetBackendHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBackendHealth",
			Handler:       _EBPFServices_StreamBackendHealth_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/ebpf_services.proto",
}
