// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/v1/ipam.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pool_name is the target pool name. If empty, pool_type is used for auto-selection.
	PoolName string `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	// pool_type selects the first auto-assign pool of this type when pool_name is empty.
	PoolType string `protobuf:"bytes,2,opt,name=pool_type,json=poolType,proto3" json:"pool_type,omitempty"`
	// owner identifies the allocating client (e.g. "novaedge", "novanet-agent").
	Owner string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	// resource is an optional K8s resource reference (e.g. "novaedge/proxyvip/my-vip").
	Resource      string `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateRequest) Reset() {
	*x = AllocateRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRequest) ProtoMessage() {}

func (x *AllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRequest.ProtoReflect.Descriptor instead.
func (*AllocateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{0}
}

func (x *AllocateRequest) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *AllocateRequest) GetPoolType() string {
	if x != nil {
		return x.PoolType
	}
	return ""
}

func (x *AllocateRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AllocateRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type AllocateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	PoolName      string                 `protobuf:"bytes,2,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateResponse) Reset() {
	*x = AllocateResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateResponse) ProtoMessage() {}

func (x *AllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateResponse.ProtoReflect.Descriptor instead.
func (*AllocateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AllocateResponse) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

type AllocateSpecificRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolName      string                 `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateSpecificRequest) Reset() {
	*x = AllocateSpecificRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateSpecificRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateSpecificRequest) ProtoMessage() {}

func (x *AllocateSpecificRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateSpecificRequest.ProtoReflect.Descriptor instead.
func (*AllocateSpecificRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{2}
}

func (x *AllocateSpecificRequest) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *AllocateSpecificRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AllocateSpecificRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AllocateSpecificRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type AllocateSpecificResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateSpecificResponse) Reset() {
	*x = AllocateSpecificResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateSpecificResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateSpecificResponse) ProtoMessage() {}

func (x *AllocateSpecificResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateSpecificResponse.ProtoReflect.Descriptor instead.
func (*AllocateSpecificResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{3}
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolName      string                 `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseRequest) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *ReleaseRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{5}
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolName      string                 `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateRequest) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *ValidateRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Available     bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type GetPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolRequest) Reset() {
	*x = GetPoolRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolRequest) ProtoMessage() {}

func (x *GetPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolRequest.ProtoReflect.Descriptor instead.
func (*GetPoolRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{8}
}

func (x *GetPoolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Allocated     int32                  `protobuf:"varint,3,opt,name=allocated,proto3" json:"allocated,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Available     int32                  `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Allocations   []*IPAllocationInfo    `protobuf:"bytes,6,rep,name=allocations,proto3" json:"allocations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolResponse) Reset() {
	*x = GetPoolResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolResponse) ProtoMessage() {}

func (x *GetPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolResponse.ProtoReflect.Descriptor instead.
func (*GetPoolResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{9}
}

func (x *GetPoolResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPoolResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetPoolResponse) GetAllocated() int32 {
	if x != nil {
		return x.Allocated
	}
	return 0
}

func (x *GetPoolResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPoolResponse) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *GetPoolResponse) GetAllocations() []*IPAllocationInfo {
	if x != nil {
		return x.Allocations
	}
	return nil
}

type ListIPPoolsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type_filter limits results to pools of this type. Empty = all.
	TypeFilter    string `protobuf:"bytes,1,opt,name=type_filter,json=typeFilter,proto3" json:"type_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIPPoolsRequest) Reset() {
	*x = ListIPPoolsRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIPPoolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIPPoolsRequest) ProtoMessage() {}

func (x *ListIPPoolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIPPoolsRequest.ProtoReflect.Descriptor instead.
func (*ListIPPoolsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{10}
}

func (x *ListIPPoolsRequest) GetTypeFilter() string {
	if x != nil {
		return x.TypeFilter
	}
	return ""
}

type ListIPPoolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pools         []*PoolInfo            `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIPPoolsResponse) Reset() {
	*x = ListIPPoolsResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIPPoolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIPPoolsResponse) ProtoMessage() {}

func (x *ListIPPoolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIPPoolsResponse.ProtoReflect.Descriptor instead.
func (*ListIPPoolsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{11}
}

func (x *ListIPPoolsResponse) GetPools() []*PoolInfo {
	if x != nil {
		return x.Pools
	}
	return nil
}

type PoolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Allocated     int32                  `protobuf:"varint,3,opt,name=allocated,proto3" json:"allocated,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Available     int32                  `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Owner         string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	AutoAssign    bool                   `protobuf:"varint,7,opt,name=auto_assign,json=autoAssign,proto3" json:"auto_assign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolInfo) Reset() {
	*x = PoolInfo{}
	mi := &file_api_v1_ipam_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolInfo) ProtoMessage() {}

func (x *PoolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolInfo.ProtoReflect.Descriptor instead.
func (*PoolInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{12}
}

func (x *PoolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PoolInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PoolInfo) GetAllocated() int32 {
	if x != nil {
		return x.Allocated
	}
	return 0
}

func (x *PoolInfo) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PoolInfo) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *PoolInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PoolInfo) GetAutoAssign() bool {
	if x != nil {
		return x.AutoAssign
	}
	return false
}

type ListIPAllocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolFilter    string                 `protobuf:"bytes,1,opt,name=pool_filter,json=poolFilter,proto3" json:"pool_filter,omitempty"`
	OwnerFilter   string                 `protobuf:"bytes,2,opt,name=owner_filter,json=ownerFilter,proto3" json:"owner_filter,omitempty"`
	TypeFilter    string                 `protobuf:"bytes,3,opt,name=type_filter,json=typeFilter,proto3" json:"type_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIPAllocationsRequest) Reset() {
	*x = ListIPAllocationsRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIPAllocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIPAllocationsRequest) ProtoMessage() {}

func (x *ListIPAllocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIPAllocationsRequest.ProtoReflect.Descriptor instead.
func (*ListIPAllocationsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{13}
}

func (x *ListIPAllocationsRequest) GetPoolFilter() string {
	if x != nil {
		return x.PoolFilter
	}
	return ""
}

func (x *ListIPAllocationsRequest) GetOwnerFilter() string {
	if x != nil {
		return x.OwnerFilter
	}
	return ""
}

func (x *ListIPAllocationsRequest) GetTypeFilter() string {
	if x != nil {
		return x.TypeFilter
	}
	return ""
}

type ListIPAllocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allocations   []*IPAllocationInfo    `protobuf:"bytes,1,rep,name=allocations,proto3" json:"allocations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIPAllocationsResponse) Reset() {
	*x = ListIPAllocationsResponse{}
	mi := &file_api_v1_ipam_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIPAllocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIPAllocationsResponse) ProtoMessage() {}

func (x *ListIPAllocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIPAllocationsResponse.ProtoReflect.Descriptor instead.
func (*ListIPAllocationsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{14}
}

func (x *ListIPAllocationsResponse) GetAllocations() []*IPAllocationInfo {
	if x != nil {
		return x.Allocations
	}
	return nil
}

type IPAllocationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,4,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAllocationInfo) Reset() {
	*x = IPAllocationInfo{}
	mi := &file_api_v1_ipam_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAllocationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAllocationInfo) ProtoMessage() {}

func (x *IPAllocationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAllocationInfo.ProtoReflect.Descriptor instead.
func (*IPAllocationInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{15}
}

func (x *IPAllocationInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPAllocationInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *IPAllocationInfo) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *IPAllocationInfo) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type WatchPoolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPoolsRequest) Reset() {
	*x = WatchPoolsRequest{}
	mi := &file_api_v1_ipam_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPoolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPoolsRequest) ProtoMessage() {}

func (x *WatchPoolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPoolsRequest.ProtoReflect.Descriptor instead.
func (*WatchPoolsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{16}
}

type PoolEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolName      string                 `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "ADDED", "MODIFIED", "DELETED"
	Pool          *PoolInfo              `protobuf:"bytes,3,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolEvent) Reset() {
	*x = PoolEvent{}
	mi := &file_api_v1_ipam_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolEvent) ProtoMessage() {}

func (x *PoolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_ipam_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolEvent.ProtoReflect.Descriptor instead.
func (*PoolEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_ipam_proto_rawDescGZIP(), []int{17}
}

func (x *PoolEvent) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *PoolEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PoolEvent) GetPool() *PoolInfo {
	if x != nil {
		return x.Pool
	}
	return nil
}

var File_api_v1_ipam_proto protoreflect.FileDescriptor

const file_api_v1_ipam_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/ipam.proto\x12\n" +
	"novanet.v1\"}\n" +
	"\x0fAllocateRequest\x12\x1b\n" +
	"\tpool_name\x18\x01 \x01(\tR\bpoolName\x12\x1b\n" +
	"\tpool_type\x18\x02 \x01(\tR\bpoolType\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\"?\n" +
	"\x10AllocateResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1b\n" +
	"\tpool_name\x18\x02 \x01(\tR\bpoolName\"x\n" +
	"\x17AllocateSpecificRequest\x12\x1b\n" +
	"\tpool_name\x18\x01 \x01(\tR\bpoolName\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\"\x1a\n" +
	"\x18AllocateSpecificResponse\"=\n" +
	"\x0eReleaseRequest\x12\x1b\n" +
	"\tpool_name\x18\x01 \x01(\tR\bpoolName\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"\x11\n" +
	"\x0fReleaseResponse\">\n" +
	"\x0fValidateRequest\x12\x1b\n" +
	"\tpool_name\x18\x01 \x01(\tR\bpoolName\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"F\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\"$\n" +
	"\x0eGetPoolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xcb\x01\n" +
	"\x0fGetPoolResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\tallocated\x18\x03 \x01(\x05R\tallocated\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\x05R\tavailable\x12>\n" +
	"\vallocations\x18\x06 \x03(\v2\x1c.novanet.v1.IPAllocationInfoR\vallocations\"5\n" +
	"\x12ListIPPoolsRequest\x12\x1f\n" +
	"\vtype_filter\x18\x01 \x01(\tR\n" +
	"typeFilter\"A\n" +
	"\x13ListIPPoolsResponse\x12*\n" +
	"\x05pools\x18\x01 \x03(\v2\x14.novanet.v1.PoolInfoR\x05pools\"\xbb\x01\n" +
	"\bPoolInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\tallocated\x18\x03 \x01(\x05R\tallocated\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\x05R\tavailable\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12\x1f\n" +
	"\vauto_assign\x18\a \x01(\bR\n" +
	"autoAssign\"\x7f\n" +
	"\x18ListIPAllocationsRequest\x12\x1f\n" +
	"\vpool_filter\x18\x01 \x01(\tR\n" +
	"poolFilter\x12!\n" +
	"\fowner_filter\x18\x02 \x01(\tR\vownerFilter\x12\x1f\n" +
	"\vtype_filter\x18\x03 \x01(\tR\n" +
	"typeFilter\"[\n" +
	"\x19ListIPAllocationsResponse\x12>\n" +
	"\vallocations\x18\x01 \x03(\v2\x1c.novanet.v1.IPAllocationInfoR\vallocations\"{\n" +
	"\x10IPAllocationInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12%\n" +
	"\x0etimestamp_unix\x18\x04 \x01(\x03R\rtimestampUnix\"\x13\n" +
	"\x11WatchPoolsRequest\"q\n" +
	"\tPoolEvent\x12\x1b\n" +
	"\tpool_name\x18\x01 \x01(\tR\bpoolName\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12(\n" +
	"\x04pool\x18\x03 \x01(\v2\x14.novanet.v1.PoolInfoR\x04pool2\xfa\x04\n" +
	"\vIPAMService\x12E\n" +
	"\bAllocate\x12\x1b.novanet.v1.AllocateRequest\x1a\x1c.novanet.v1.AllocateResponse\x12]\n" +
	"\x10AllocateSpecific\x12#.novanet.v1.AllocateSpecificRequest\x1a$.novanet.v1.AllocateSpecificResponse\x12B\n" +
	"\aRelease\x12\x1a.novanet.v1.ReleaseRequest\x1a\x1b.novanet.v1.ReleaseResponse\x12E\n" +
	"\bValidate\x12\x1b.novanet.v1.ValidateRequest\x1a\x1c.novanet.v1.ValidateResponse\x12B\n" +
	"\aGetPool\x12\x1a.novanet.v1.GetPoolRequest\x1a\x1b.novanet.v1.GetPoolResponse\x12N\n" +
	"\vListIPPools\x12\x1e.novanet.v1.ListIPPoolsRequest\x1a\x1f.novanet.v1.ListIPPoolsResponse\x12`\n" +
	"\x11ListIPAllocations\x12$.novanet.v1.ListIPAllocationsRequest\x1a%.novanet.v1.ListIPAllocationsResponse\x12D\n" +
	"\n" +
	"WatchPools\x12\x1d.novanet.v1.WatchPoolsRequest\x1a\x15.novanet.v1.PoolEvent0\x01B$Z\"github.com/azrtydxb/novanet/api/v1b\x06proto3"

var (
	file_api_v1_ipam_proto_rawDescOnce sync.Once
	file_api_v1_ipam_proto_rawDescData []byte
)

func file_api_v1_ipam_proto_rawDescGZIP() []byte {
	file_api_v1_ipam_proto_rawDescOnce.Do(func() {
		file_api_v1_ipam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_ipam_proto_rawDesc), len(file_api_v1_ipam_proto_rawDesc)))
	})
	return file_api_v1_ipam_proto_rawDescData
}

var file_api_v1_ipam_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_v1_ipam_proto_goTypes = []any{
	(*AllocateRequest)(nil),           // 0: novanet.v1.AllocateRequest
	(*AllocateResponse)(nil),          // 1: novanet.v1.AllocateResponse
	(*AllocateSpecificRequest)(nil),   // 2: novanet.v1.AllocateSpecificRequest
	(*AllocateSpecificResponse)(nil),  // 3: novanet.v1.AllocateSpecificResponse
	(*ReleaseRequest)(nil),            // 4: novanet.v1.ReleaseRequest
	(*ReleaseResponse)(nil),           // 5: novanet.v1.ReleaseResponse
	(*ValidateRequest)(nil),           // 6: novanet.v1.ValidateRequest
	(*ValidateResponse)(nil),          // 7: novanet.v1.ValidateResponse
	(*GetPoolRequest)(nil),            // 8: novanet.v1.GetPoolRequest
	(*GetPoolResponse)(nil),           // 9: novanet.v1.GetPoolResponse
	(*ListIPPoolsRequest)(nil),        // 10: novanet.v1.ListIPPoolsRequest
	(*ListIPPoolsResponse)(nil),       // 11: novanet.v1.ListIPPoolsResponse
	(*PoolInfo)(nil),                  // 12: novanet.v1.PoolInfo
	(*ListIPAllocationsRequest)(nil),  // 13: novanet.v1.ListIPAllocationsRequest
	(*ListIPAllocationsResponse)(nil), // 14: novanet.v1.ListIPAllocationsResponse
	(*IPAllocationInfo)(nil),          // 15: novanet.v1.IPAllocationInfo
	(*WatchPoolsRequest)(nil),         // 16: novanet.v1.WatchPoolsRequest
	(*PoolEvent)(nil),                 // 17: novanet.v1.PoolEvent
}
var file_api_v1_ipam_proto_depIdxs = []int32{
	15, // 0: novanet.v1.GetPoolResponse.allocations:type_name -> novanet.v1.IPAllocationInfo
	12, // 1: novanet.v1.ListIPPoolsResponse.pools:type_name -> novanet.v1.PoolInfo
	15, // 2: novanet.v1.ListIPAllocationsResponse.allocations:type_name -> novanet.v1.IPAllocationInfo
	12, // 3: novanet.v1.PoolEvent.pool:type_name -> novanet.v1.PoolInfo
	0,  // 4: novanet.v1.IPAMService.Allocate:input_type -> novanet.v1.AllocateRequest
	2,  // 5: novanet.v1.IPAMService.AllocateSpecific:input_type -> novanet.v1.AllocateSpecificRequest
	4,  // 6: novanet.v1.IPAMService.Release:input_type -> novanet.v1.ReleaseRequest
	6,  // 7: novanet.v1.IPAMService.Validate:input_type -> novanet.v1.ValidateRequest
	8,  // 8: novanet.v1.IPAMService.GetPool:input_type -> novanet.v1.GetPoolRequest
	10, // 9: novanet.v1.IPAMService.ListIPPools:input_type -> novanet.v1.ListIPPoolsRequest
	13, // 10: novanet.v1.IPAMService.ListIPAllocations:input_type -> novanet.v1.ListIPAllocationsRequest
	16, // 11: novanet.v1.IPAMService.WatchPools:input_type -> novanet.v1.WatchPoolsRequest
	1,  // 12: novanet.v1.IPAMService.Allocate:output_type -> novanet.v1.AllocateResponse
	3,  // 13: novanet.v1.IPAMService.AllocateSpecific:output_type -> novanet.v1.AllocateSpecificResponse
	5,  // 14: novanet.v1.IPAMService.Release:output_type -> novanet.v1.ReleaseResponse
	7,  // 15: novanet.v1.IPAMService.Validate:output_type -> novanet.v1.ValidateResponse
	9,  // 16: novanet.v1.IPAMService.GetPool:output_type -> novanet.v1.GetPoolResponse
	11, // 17: novanet.v1.IPAMService.ListIPPools:output_type -> novanet.v1.ListIPPoolsResponse
	14, // 18: novanet.v1.IPAMService.ListIPAllocations:output_type -> novanet.v1.ListIPAllocationsResponse
	17, // 19: novanet.v1.IPAMService.WatchPools:output_type -> novanet.v1.PoolEvent
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_ipam_proto_init() }
func file_api_v1_ipam_proto_init() {
	if File_api_v1_ipam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_ipam_proto_rawDesc), len(file_api_v1_ipam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_ipam_proto_goTypes,
		DependencyIndexes: file_api_v1_ipam_proto_depIdxs,
		MessageInfos:      file_api_v1_ipam_proto_msgTypes,
	}.Build()
	File_api_v1_ipam_proto = out.File
	file_api_v1_ipam_proto_goTypes = nil
	file_api_v1_ipam_proto_depIdxs = nil
}
