// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/v1/ipam.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IPAMService_Allocate_FullMethodName          = "/novanet.v1.IPAMService/Allocate"
	IPAMService_AllocateSpecific_FullMethodName  = "/novanet.v1.IPAMService/AllocateSpecific"
	IPAMService_Release_FullMethodName           = "/novanet.v1.IPAMService/Release"
	IPAMService_Validate_FullMethodName          = "/novanet.v1.IPAMService/Validate"
	IPAMService_GetPool_FullMethodName           = "/novanet.v1.IPAMService/GetPool"
	IPAMService_ListIPPools_FullMethodName       = "/novanet.v1.IPAMService/ListIPPools"
	IPAMService_ListIPAllocations_FullMethodName = "/novanet.v1.IPAMService/ListIPAllocations"
	IPAMService_WatchPools_FullMethodName        = "/novanet.v1.IPAMService/WatchPools"
)

// IPAMServiceClient is the client API for IPAMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IPAMService provides cluster-wide IP address management for the Nova
// ecosystem. All Nova projects (NovaEdge, NovaRoute, NovaNet) can consume
// this service via a Unix domain socket at /run/novanet/ipam.sock.
type IPAMServiceClient interface {
	// Allocate requests the next available IP from a pool (by name or type).
	Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error)
	// AllocateSpecific requests a specific IP from a pool.
	AllocateSpecific(ctx context.Context, in *AllocateSpecificRequest, opts ...grpc.CallOption) (*AllocateSpecificResponse, error)
	// Release releases a previously allocated IP.
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	// Validate checks if an IP is valid and available in a pool.
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	// GetPool returns pool status and allocation info.
	GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*GetPoolResponse, error)
	// ListPools lists all pools with optional type filter.
	ListIPPools(ctx context.Context, in *ListIPPoolsRequest, opts ...grpc.CallOption) (*ListIPPoolsResponse, error)
	// ListAllocations lists allocations with owner/pool/type filters.
	ListIPAllocations(ctx context.Context, in *ListIPAllocationsRequest, opts ...grpc.CallOption) (*ListIPAllocationsResponse, error)
	// WatchPools provides a server-streaming RPC for pool change events.
	WatchPools(ctx context.Context, in *WatchPoolsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PoolEvent], error)
}

type iPAMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIPAMServiceClient(cc grpc.ClientConnInterface) IPAMServiceClient {
	return &iPAMServiceClient{cc}
}

func (c *iPAMServiceClient) Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateResponse)
	err := c.cc.Invoke(ctx, IPAMService_Allocate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPAMServiceClient) AllocateSpecific(ctx context.Context, in *AllocateSpecificRequest, opts ...grpc.CallOption) (*AllocateSpecificResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateSpecificResponse)
	err := c.cc.Invoke(ctx, IPAMService_AllocateSpecific_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPAMServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, IPAMService_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPAMServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, IPAMService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPAMServiceClient) GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*GetPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPoolResponse)
	err := c.cc.Invoke(ctx, IPAMService_GetPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPAMServiceClient) ListIPPools(ctx context.Context, in *ListIPPoolsRequest, opts ...grpc.CallOption) (*ListIPPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIPPoolsResponse)
	err := c.cc.Invoke(ctx, IPAMService_ListIPPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPAMServiceClient) ListIPAllocations(ctx context.Context, in *ListIPAllocationsRequest, opts ...grpc.CallOption) (*ListIPAllocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIPAllocationsResponse)
	err := c.cc.Invoke(ctx, IPAMService_ListIPAllocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPAMServiceClient) WatchPools(ctx context.Context, in *WatchPoolsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PoolEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IPAMService_ServiceDesc.Streams[0], IPAMService_WatchPools_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPoolsRequest, PoolEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IPAMService_WatchPoolsClient = grpc.ServerStreamingClient[PoolEvent]

// IPAMServiceServer is the server API for IPAMService service.
// All implementations must embed UnimplementedIPAMServiceServer
// for forward compatibility.
//
// IPAMService provides cluster-wide IP address management for the Nova
// ecosystem. All Nova projects (NovaEdge, NovaRoute, NovaNet) can consume
// this service via a Unix domain socket at /run/novanet/ipam.sock.
type IPAMServiceServer interface {
	// Allocate requests the next available IP from a pool (by name or type).
	Allocate(context.Context, *AllocateRequest) (*AllocateResponse, error)
	// AllocateSpecific requests a specific IP from a pool.
	AllocateSpecific(context.Context, *AllocateSpecificRequest) (*AllocateSpecificResponse, error)
	// Release releases a previously allocated IP.
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	// Validate checks if an IP is valid and available in a pool.
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	// GetPool returns pool status and allocation info.
	GetPool(context.Context, *GetPoolRequest) (*GetPoolResponse, error)
	// ListPools lists all pools with optional type filter.
	ListIPPools(context.Context, *ListIPPoolsRequest) (*ListIPPoolsResponse, error)
	// ListAllocations lists allocations with owner/pool/type filters.
	ListIPAllocations(context.Context, *ListIPAllocationsRequest) (*ListIPAllocationsResponse, error)
	// WatchPools provides a server-streaming RPC for pool change events.
	WatchPools(*WatchPoolsRequest, grpc.ServerStreamingServer[PoolEvent]) error
	mustEmbedUnimplementedIPAMServiceServer()
}

// UnimplementedIPAMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIPAMServiceServer struct{}

func (UnimplementedIPAMServiceServer) Allocate(context.Context, *AllocateRequest) (*AllocateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedIPAMServiceServer) AllocateSpecific(context.Context, *AllocateSpecificRequest) (*AllocateSpecificResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocateSpecific not implemented")
}
func (UnimplementedIPAMServiceServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedIPAMServiceServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedIPAMServiceServer) GetPool(context.Context, *GetPoolRequest) (*GetPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPool not implemented")
}
func (UnimplementedIPAMServiceServer) ListIPPools(context.Context, *ListIPPoolsRequest) (*ListIPPoolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIPPools not implemented")
}
func (UnimplementedIPAMServiceServer) ListIPAllocations(context.Context, *ListIPAllocationsRequest) (*ListIPAllocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIPAllocations not implemented")
}
func (UnimplementedIPAMServiceServer) WatchPools(*WatchPoolsRequest, grpc.ServerStreamingServer[PoolEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchPools not implemented")
}
func (UnimplementedIPAMServiceServer) mustEmbedUnimplementedIPAMServiceServer() {}
func (UnimplementedIPAMServiceServer) testEmbeddedByValue()                     {}

// UnsafeIPAMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IPAMServiceServer will
// result in compilation errors.
type UnsafeIPAMServiceServer interface {
	mustEmbedUnimplementedIPAMServiceServer()
}

func RegisterIPAMServiceServer(s grpc.ServiceRegistrar, srv IPAMServiceServer) {
	// If the following call panics, it indicates UnimplementedIPAMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IPAMService_ServiceDesc, srv)
}

func _IPAMService_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAMServiceServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAMService_Allocate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAMServiceServer).Allocate(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPAMService_AllocateSpecific_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateSpecificRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAMServiceServer).AllocateSpecific(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAMService_AllocateSpecific_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAMServiceServer).AllocateSpecific(ctx, req.(*AllocateSpecificRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPAMService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAMServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAMService_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAMServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPAMService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAMServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAMService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAMServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPAMService_GetPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAMServiceServer).GetPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAMService_GetPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAMServiceServer).GetPool(ctx, req.(*GetPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPAMService_ListIPPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIPPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAMServiceServer).ListIPPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAMService_ListIPPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAMServiceServer).ListIPPools(ctx, req.(*ListIPPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPAMService_ListIPAllocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIPAllocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAMServiceServer).ListIPAllocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAMService_ListIPAllocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAMServiceServer).ListIPAllocations(ctx, req.(*ListIPAllocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPAMService_WatchPools_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPoolsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IPAMServiceServer).WatchPools(m, &grpc.GenericServerStream[WatchPoolsRequest, PoolEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IPAMService_WatchPoolsServer = grpc.ServerStreamingServer[PoolEvent]

// IPAMService_ServiceDesc is the grpc.ServiceDesc for IPAMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IPAMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novanet.v1.IPAMService",
	HandlerType: (*IPAMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allocate",
			Handler:    _IPAMService_Allocate_Handler,
		},
		{
			MethodName: "AllocateSpecific",
			Handler:    _IPAMService_AllocateSpecific_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _IPAMService_Release_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _IPAMService_Validate_Handler,
		},
		{
			MethodName: "GetPool",
			Handler:    _IPAMService_GetPool_Handler,
		},
		{
			MethodName: "ListIPPools",
			Handler:    _IPAMService_ListIPPools_Handler,
		},
		{
			MethodName: "ListIPAllocations",
			Handler:    _IPAMService_ListIPAllocations_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPools",
			Handler:       _IPAMService_WatchPools_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/ipam.proto",
}
