// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/v1/novanet.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataplaneControl_UpsertEndpoint_FullMethodName     = "/novanet.v1.DataplaneControl/UpsertEndpoint"
	DataplaneControl_DeleteEndpoint_FullMethodName     = "/novanet.v1.DataplaneControl/DeleteEndpoint"
	DataplaneControl_UpsertPolicy_FullMethodName       = "/novanet.v1.DataplaneControl/UpsertPolicy"
	DataplaneControl_DeletePolicy_FullMethodName       = "/novanet.v1.DataplaneControl/DeletePolicy"
	DataplaneControl_SyncPolicies_FullMethodName       = "/novanet.v1.DataplaneControl/SyncPolicies"
	DataplaneControl_UpsertTunnel_FullMethodName       = "/novanet.v1.DataplaneControl/UpsertTunnel"
	DataplaneControl_DeleteTunnel_FullMethodName       = "/novanet.v1.DataplaneControl/DeleteTunnel"
	DataplaneControl_UpdateConfig_FullMethodName       = "/novanet.v1.DataplaneControl/UpdateConfig"
	DataplaneControl_AttachProgram_FullMethodName      = "/novanet.v1.DataplaneControl/AttachProgram"
	DataplaneControl_DetachProgram_FullMethodName      = "/novanet.v1.DataplaneControl/DetachProgram"
	DataplaneControl_UpsertEgressPolicy_FullMethodName = "/novanet.v1.DataplaneControl/UpsertEgressPolicy"
	DataplaneControl_DeleteEgressPolicy_FullMethodName = "/novanet.v1.DataplaneControl/DeleteEgressPolicy"
	DataplaneControl_StreamFlows_FullMethodName        = "/novanet.v1.DataplaneControl/StreamFlows"
	DataplaneControl_GetDataplaneStatus_FullMethodName = "/novanet.v1.DataplaneControl/GetDataplaneStatus"
)

// DataplaneControlClient is the client API for DataplaneControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataplaneControl is the internal API between the Go management plane
// and the Rust eBPF dataplane. The Rust dataplane runs the gRPC server,
// the Go agent is the client.
type DataplaneControlClient interface {
	// Endpoint management
	UpsertEndpoint(ctx context.Context, in *UpsertEndpointRequest, opts ...grpc.CallOption) (*UpsertEndpointResponse, error)
	DeleteEndpoint(ctx context.Context, in *DeleteEndpointRequest, opts ...grpc.CallOption) (*DeleteEndpointResponse, error)
	// Policy management
	UpsertPolicy(ctx context.Context, in *UpsertPolicyRequest, opts ...grpc.CallOption) (*UpsertPolicyResponse, error)
	DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*DeletePolicyResponse, error)
	SyncPolicies(ctx context.Context, in *SyncPoliciesRequest, opts ...grpc.CallOption) (*SyncPoliciesResponse, error)
	// Tunnel management (overlay mode)
	UpsertTunnel(ctx context.Context, in *UpsertTunnelRequest, opts ...grpc.CallOption) (*UpsertTunnelResponse, error)
	DeleteTunnel(ctx context.Context, in *DeleteTunnelRequest, opts ...grpc.CallOption) (*DeleteTunnelResponse, error)
	// Configuration
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	// TC program lifecycle
	AttachProgram(ctx context.Context, in *AttachProgramRequest, opts ...grpc.CallOption) (*AttachProgramResponse, error)
	DetachProgram(ctx context.Context, in *DetachProgramRequest, opts ...grpc.CallOption) (*DetachProgramResponse, error)
	// Egress policy management
	UpsertEgressPolicy(ctx context.Context, in *UpsertEgressPolicyRequest, opts ...grpc.CallOption) (*UpsertEgressPolicyResponse, error)
	DeleteEgressPolicy(ctx context.Context, in *DeleteEgressPolicyRequest, opts ...grpc.CallOption) (*DeleteEgressPolicyResponse, error)
	// Observability
	StreamFlows(ctx context.Context, in *StreamFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowEvent], error)
	GetDataplaneStatus(ctx context.Context, in *GetDataplaneStatusRequest, opts ...grpc.CallOption) (*GetDataplaneStatusResponse, error)
}

type dataplaneControlClient struct {
	cc grpc.ClientConnInterface
}

func NewDataplaneControlClient(cc grpc.ClientConnInterface) DataplaneControlClient {
	return &dataplaneControlClient{cc}
}

func (c *dataplaneControlClient) UpsertEndpoint(ctx context.Context, in *UpsertEndpointRequest, opts ...grpc.CallOption) (*UpsertEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertEndpointResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteEndpoint(ctx context.Context, in *DeleteEndpointRequest, opts ...grpc.CallOption) (*DeleteEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEndpointResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertPolicy(ctx context.Context, in *UpsertPolicyRequest, opts ...grpc.CallOption) (*UpsertPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertPolicyResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*DeletePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePolicyResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeletePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) SyncPolicies(ctx context.Context, in *SyncPoliciesRequest, opts ...grpc.CallOption) (*SyncPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncPoliciesResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_SyncPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertTunnel(ctx context.Context, in *UpsertTunnelRequest, opts ...grpc.CallOption) (*UpsertTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertTunnelResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteTunnel(ctx context.Context, in *DeleteTunnelRequest, opts ...grpc.CallOption) (*DeleteTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTunnelResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) AttachProgram(ctx context.Context, in *AttachProgramRequest, opts ...grpc.CallOption) (*AttachProgramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachProgramResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_AttachProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DetachProgram(ctx context.Context, in *DetachProgramRequest, opts ...grpc.CallOption) (*DetachProgramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachProgramResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DetachProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertEgressPolicy(ctx context.Context, in *UpsertEgressPolicyRequest, opts ...grpc.CallOption) (*UpsertEgressPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertEgressPolicyResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertEgressPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteEgressPolicy(ctx context.Context, in *DeleteEgressPolicyRequest, opts ...grpc.CallOption) (*DeleteEgressPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEgressPolicyResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteEgressPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) StreamFlows(ctx context.Context, in *StreamFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataplaneControl_ServiceDesc.Streams[0], DataplaneControl_StreamFlows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFlowsRequest, FlowEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneControl_StreamFlowsClient = grpc.ServerStreamingClient[FlowEvent]

func (c *dataplaneControlClient) GetDataplaneStatus(ctx context.Context, in *GetDataplaneStatusRequest, opts ...grpc.CallOption) (*GetDataplaneStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataplaneStatusResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_GetDataplaneStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataplaneControlServer is the server API for DataplaneControl service.
// All implementations must embed UnimplementedDataplaneControlServer
// for forward compatibility.
//
// DataplaneControl is the internal API between the Go management plane
// and the Rust eBPF dataplane. The Rust dataplane runs the gRPC server,
// the Go agent is the client.
type DataplaneControlServer interface {
	// Endpoint management
	UpsertEndpoint(context.Context, *UpsertEndpointRequest) (*UpsertEndpointResponse, error)
	DeleteEndpoint(context.Context, *DeleteEndpointRequest) (*DeleteEndpointResponse, error)
	// Policy management
	UpsertPolicy(context.Context, *UpsertPolicyRequest) (*UpsertPolicyResponse, error)
	DeletePolicy(context.Context, *DeletePolicyRequest) (*DeletePolicyResponse, error)
	SyncPolicies(context.Context, *SyncPoliciesRequest) (*SyncPoliciesResponse, error)
	// Tunnel management (overlay mode)
	UpsertTunnel(context.Context, *UpsertTunnelRequest) (*UpsertTunnelResponse, error)
	DeleteTunnel(context.Context, *DeleteTunnelRequest) (*DeleteTunnelResponse, error)
	// Configuration
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	// TC program lifecycle
	AttachProgram(context.Context, *AttachProgramRequest) (*AttachProgramResponse, error)
	DetachProgram(context.Context, *DetachProgramRequest) (*DetachProgramResponse, error)
	// Egress policy management
	UpsertEgressPolicy(context.Context, *UpsertEgressPolicyRequest) (*UpsertEgressPolicyResponse, error)
	DeleteEgressPolicy(context.Context, *DeleteEgressPolicyRequest) (*DeleteEgressPolicyResponse, error)
	// Observability
	StreamFlows(*StreamFlowsRequest, grpc.ServerStreamingServer[FlowEvent]) error
	GetDataplaneStatus(context.Context, *GetDataplaneStatusRequest) (*GetDataplaneStatusResponse, error)
	mustEmbedUnimplementedDataplaneControlServer()
}

// UnimplementedDataplaneControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataplaneControlServer struct{}

func (UnimplementedDataplaneControlServer) UpsertEndpoint(context.Context, *UpsertEndpointRequest) (*UpsertEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertEndpoint not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteEndpoint(context.Context, *DeleteEndpointRequest) (*DeleteEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEndpoint not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertPolicy(context.Context, *UpsertPolicyRequest) (*UpsertPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertPolicy not implemented")
}
func (UnimplementedDataplaneControlServer) DeletePolicy(context.Context, *DeletePolicyRequest) (*DeletePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePolicy not implemented")
}
func (UnimplementedDataplaneControlServer) SyncPolicies(context.Context, *SyncPoliciesRequest) (*SyncPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncPolicies not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertTunnel(context.Context, *UpsertTunnelRequest) (*UpsertTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertTunnel not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteTunnel(context.Context, *DeleteTunnelRequest) (*DeleteTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTunnel not implemented")
}
func (UnimplementedDataplaneControlServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedDataplaneControlServer) AttachProgram(context.Context, *AttachProgramRequest) (*AttachProgramResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachProgram not implemented")
}
func (UnimplementedDataplaneControlServer) DetachProgram(context.Context, *DetachProgramRequest) (*DetachProgramResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachProgram not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertEgressPolicy(context.Context, *UpsertEgressPolicyRequest) (*UpsertEgressPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertEgressPolicy not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteEgressPolicy(context.Context, *DeleteEgressPolicyRequest) (*DeleteEgressPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEgressPolicy not implemented")
}
func (UnimplementedDataplaneControlServer) StreamFlows(*StreamFlowsRequest, grpc.ServerStreamingServer[FlowEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamFlows not implemented")
}
func (UnimplementedDataplaneControlServer) GetDataplaneStatus(context.Context, *GetDataplaneStatusRequest) (*GetDataplaneStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDataplaneStatus not implemented")
}
func (UnimplementedDataplaneControlServer) mustEmbedUnimplementedDataplaneControlServer() {}
func (UnimplementedDataplaneControlServer) testEmbeddedByValue()                          {}

// UnsafeDataplaneControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataplaneControlServer will
// result in compilation errors.
type UnsafeDataplaneControlServer interface {
	mustEmbedUnimplementedDataplaneControlServer()
}

func RegisterDataplaneControlServer(s grpc.ServiceRegistrar, srv DataplaneControlServer) {
	// If the following call panics, it indicates UnimplementedDataplaneControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataplaneControl_ServiceDesc, srv)
}

func _DataplaneControl_UpsertEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertEndpoint(ctx, req.(*UpsertEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteEndpoint(ctx, req.(*DeleteEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertPolicy(ctx, req.(*UpsertPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeletePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeletePolicy(ctx, req.(*DeletePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_SyncPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).SyncPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_SyncPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).SyncPolicies(ctx, req.(*SyncPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertTunnel(ctx, req.(*UpsertTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteTunnel(ctx, req.(*DeleteTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_AttachProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).AttachProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_AttachProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).AttachProgram(ctx, req.(*AttachProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DetachProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DetachProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DetachProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DetachProgram(ctx, req.(*DetachProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertEgressPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertEgressPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertEgressPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertEgressPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertEgressPolicy(ctx, req.(*UpsertEgressPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteEgressPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEgressPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteEgressPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteEgressPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteEgressPolicy(ctx, req.(*DeleteEgressPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_StreamFlows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamFlowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataplaneControlServer).StreamFlows(m, &grpc.GenericServerStream[StreamFlowsRequest, FlowEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneControl_StreamFlowsServer = grpc.ServerStreamingServer[FlowEvent]

func _DataplaneControl_GetDataplaneStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataplaneStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).GetDataplaneStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_GetDataplaneStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).GetDataplaneStatus(ctx, req.(*GetDataplaneStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataplaneControl_ServiceDesc is the grpc.ServiceDesc for DataplaneControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataplaneControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novanet.v1.DataplaneControl",
	HandlerType: (*DataplaneControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertEndpoint",
			Handler:    _DataplaneControl_UpsertEndpoint_Handler,
		},
		{
			MethodName: "DeleteEndpoint",
			Handler:    _DataplaneControl_DeleteEndpoint_Handler,
		},
		{
			MethodName: "UpsertPolicy",
			Handler:    _DataplaneControl_UpsertPolicy_Handler,
		},
		{
			MethodName: "DeletePolicy",
			Handler:    _DataplaneControl_DeletePolicy_Handler,
		},
		{
			MethodName: "SyncPolicies",
			Handler:    _DataplaneControl_SyncPolicies_Handler,
		},
		{
			MethodName: "UpsertTunnel",
			Handler:    _DataplaneControl_UpsertTunnel_Handler,
		},
		{
			MethodName: "DeleteTunnel",
			Handler:    _DataplaneControl_DeleteTunnel_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _DataplaneControl_UpdateConfig_Handler,
		},
		{
			MethodName: "AttachProgram",
			Handler:    _DataplaneControl_AttachProgram_Handler,
		},
		{
			MethodName: "DetachProgram",
			Handler:    _DataplaneControl_DetachProgram_Handler,
		},
		{
			MethodName: "UpsertEgressPolicy",
			Handler:    _DataplaneControl_UpsertEgressPolicy_Handler,
		},
		{
			MethodName: "DeleteEgressPolicy",
			Handler:    _DataplaneControl_DeleteEgressPolicy_Handler,
		},
		{
			MethodName: "GetDataplaneStatus",
			Handler:    _DataplaneControl_GetDataplaneStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFlows",
			Handler:       _DataplaneControl_StreamFlows_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/novanet.proto",
}

const (
	AgentControl_AddPod_FullMethodName             = "/novanet.v1.AgentControl/AddPod"
	AgentControl_DelPod_FullMethodName             = "/novanet.v1.AgentControl/DelPod"
	AgentControl_GetAgentStatus_FullMethodName     = "/novanet.v1.AgentControl/GetAgentStatus"
	AgentControl_StreamAgentFlows_FullMethodName   = "/novanet.v1.AgentControl/StreamAgentFlows"
	AgentControl_ListPolicies_FullMethodName       = "/novanet.v1.AgentControl/ListPolicies"
	AgentControl_ListIdentities_FullMethodName     = "/novanet.v1.AgentControl/ListIdentities"
	AgentControl_ListTunnels_FullMethodName        = "/novanet.v1.AgentControl/ListTunnels"
	AgentControl_ListEgressPolicies_FullMethodName = "/novanet.v1.AgentControl/ListEgressPolicies"
)

// AgentControlClient is the client API for AgentControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentControl is the API exposed by the Go agent for CNI binary
// and CLI tool connections.
type AgentControlClient interface {
	// CNI operations
	AddPod(ctx context.Context, in *AddPodRequest, opts ...grpc.CallOption) (*AddPodResponse, error)
	DelPod(ctx context.Context, in *DelPodRequest, opts ...grpc.CallOption) (*DelPodResponse, error)
	// Status
	GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*GetAgentStatusResponse, error)
	// Flow streaming (proxied from dataplane)
	StreamAgentFlows(ctx context.Context, in *StreamAgentFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowEvent], error)
	// List RPCs (CLI)
	ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error)
	ListIdentities(ctx context.Context, in *ListIdentitiesRequest, opts ...grpc.CallOption) (*ListIdentitiesResponse, error)
	ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error)
	ListEgressPolicies(ctx context.Context, in *ListEgressPoliciesRequest, opts ...grpc.CallOption) (*ListEgressPoliciesResponse, error)
}

type agentControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlClient(cc grpc.ClientConnInterface) AgentControlClient {
	return &agentControlClient{cc}
}

func (c *agentControlClient) AddPod(ctx context.Context, in *AddPodRequest, opts ...grpc.CallOption) (*AddPodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPodResponse)
	err := c.cc.Invoke(ctx, AgentControl_AddPod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) DelPod(ctx context.Context, in *DelPodRequest, opts ...grpc.CallOption) (*DelPodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelPodResponse)
	err := c.cc.Invoke(ctx, AgentControl_DelPod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*GetAgentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentStatusResponse)
	err := c.cc.Invoke(ctx, AgentControl_GetAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) StreamAgentFlows(ctx context.Context, in *StreamAgentFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControl_ServiceDesc.Streams[0], AgentControl_StreamAgentFlows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAgentFlowsRequest, FlowEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_StreamAgentFlowsClient = grpc.ServerStreamingClient[FlowEvent]

func (c *agentControlClient) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoliciesResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ListIdentities(ctx context.Context, in *ListIdentitiesRequest, opts ...grpc.CallOption) (*ListIdentitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIdentitiesResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTunnelsResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListTunnels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ListEgressPolicies(ctx context.Context, in *ListEgressPoliciesRequest, opts ...grpc.CallOption) (*ListEgressPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEgressPoliciesResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListEgressPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentControlServer is the server API for AgentControl service.
// All implementations must embed UnimplementedAgentControlServer
// for forward compatibility.
//
// AgentControl is the API exposed by the Go agent for CNI binary
// and CLI tool connections.
type AgentControlServer interface {
	// CNI operations
	AddPod(context.Context, *AddPodRequest) (*AddPodResponse, error)
	DelPod(context.Context, *DelPodRequest) (*DelPodResponse, error)
	// Status
	GetAgentStatus(context.Context, *GetAgentStatusRequest) (*GetAgentStatusResponse, error)
	// Flow streaming (proxied from dataplane)
	StreamAgentFlows(*StreamAgentFlowsRequest, grpc.ServerStreamingServer[FlowEvent]) error
	// List RPCs (CLI)
	ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error)
	ListIdentities(context.Context, *ListIdentitiesRequest) (*ListIdentitiesResponse, error)
	ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error)
	ListEgressPolicies(context.Context, *ListEgressPoliciesRequest) (*ListEgressPoliciesResponse, error)
	mustEmbedUnimplementedAgentControlServer()
}

// UnimplementedAgentControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlServer struct{}

func (UnimplementedAgentControlServer) AddPod(context.Context, *AddPodRequest) (*AddPodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPod not implemented")
}
func (UnimplementedAgentControlServer) DelPod(context.Context, *DelPodRequest) (*DelPodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelPod not implemented")
}
func (UnimplementedAgentControlServer) GetAgentStatus(context.Context, *GetAgentStatusRequest) (*GetAgentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentStatus not implemented")
}
func (UnimplementedAgentControlServer) StreamAgentFlows(*StreamAgentFlowsRequest, grpc.ServerStreamingServer[FlowEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamAgentFlows not implemented")
}
func (UnimplementedAgentControlServer) ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedAgentControlServer) ListIdentities(context.Context, *ListIdentitiesRequest) (*ListIdentitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIdentities not implemented")
}
func (UnimplementedAgentControlServer) ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTunnels not implemented")
}
func (UnimplementedAgentControlServer) ListEgressPolicies(context.Context, *ListEgressPoliciesRequest) (*ListEgressPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEgressPolicies not implemented")
}
func (UnimplementedAgentControlServer) mustEmbedUnimplementedAgentControlServer() {}
func (UnimplementedAgentControlServer) testEmbeddedByValue()                      {}

// UnsafeAgentControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlServer will
// result in compilation errors.
type UnsafeAgentControlServer interface {
	mustEmbedUnimplementedAgentControlServer()
}

func RegisterAgentControlServer(s grpc.ServiceRegistrar, srv AgentControlServer) {
	// If the following call panics, it indicates UnimplementedAgentControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControl_ServiceDesc, srv)
}

func _AgentControl_AddPod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).AddPod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_AddPod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).AddPod(ctx, req.(*AddPodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_DelPod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelPodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).DelPod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_DelPod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).DelPod(ctx, req.(*DelPodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetAgentStatus(ctx, req.(*GetAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_StreamAgentFlows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAgentFlowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentControlServer).StreamAgentFlows(m, &grpc.GenericServerStream[StreamAgentFlowsRequest, FlowEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_StreamAgentFlowsServer = grpc.ServerStreamingServer[FlowEvent]

func _AgentControl_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListPolicies(ctx, req.(*ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ListIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListIdentities(ctx, req.(*ListIdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ListTunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTunnelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListTunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListTunnels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListTunnels(ctx, req.(*ListTunnelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ListEgressPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEgressPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListEgressPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListEgressPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListEgressPolicies(ctx, req.(*ListEgressPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentControl_ServiceDesc is the grpc.ServiceDesc for AgentControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novanet.v1.AgentControl",
	HandlerType: (*AgentControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPod",
			Handler:    _AgentControl_AddPod_Handler,
		},
		{
			MethodName: "DelPod",
			Handler:    _AgentControl_DelPod_Handler,
		},
		{
			MethodName: "GetAgentStatus",
			Handler:    _AgentControl_GetAgentStatus_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _AgentControl_ListPolicies_Handler,
		},
		{
			MethodName: "ListIdentities",
			Handler:    _AgentControl_ListIdentities_Handler,
		},
		{
			MethodName: "ListTunnels",
			Handler:    _AgentControl_ListTunnels_Handler,
		},
		{
			MethodName: "ListEgressPolicies",
			Handler:    _AgentControl_ListEgressPolicies_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAgentFlows",
			Handler:       _AgentControl_StreamAgentFlows_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/novanet.proto",
}
