// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/v1/novanet.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataplaneControl_UpsertEndpoint_FullMethodName            = "/novanet.v1.DataplaneControl/UpsertEndpoint"
	DataplaneControl_DeleteEndpoint_FullMethodName            = "/novanet.v1.DataplaneControl/DeleteEndpoint"
	DataplaneControl_UpsertPolicy_FullMethodName              = "/novanet.v1.DataplaneControl/UpsertPolicy"
	DataplaneControl_DeletePolicy_FullMethodName              = "/novanet.v1.DataplaneControl/DeletePolicy"
	DataplaneControl_SyncPolicies_FullMethodName              = "/novanet.v1.DataplaneControl/SyncPolicies"
	DataplaneControl_UpsertTunnel_FullMethodName              = "/novanet.v1.DataplaneControl/UpsertTunnel"
	DataplaneControl_DeleteTunnel_FullMethodName              = "/novanet.v1.DataplaneControl/DeleteTunnel"
	DataplaneControl_UpdateConfig_FullMethodName              = "/novanet.v1.DataplaneControl/UpdateConfig"
	DataplaneControl_AttachProgram_FullMethodName             = "/novanet.v1.DataplaneControl/AttachProgram"
	DataplaneControl_DetachProgram_FullMethodName             = "/novanet.v1.DataplaneControl/DetachProgram"
	DataplaneControl_UpsertEgressPolicy_FullMethodName        = "/novanet.v1.DataplaneControl/UpsertEgressPolicy"
	DataplaneControl_DeleteEgressPolicy_FullMethodName        = "/novanet.v1.DataplaneControl/DeleteEgressPolicy"
	DataplaneControl_UpsertService_FullMethodName             = "/novanet.v1.DataplaneControl/UpsertService"
	DataplaneControl_DeleteService_FullMethodName             = "/novanet.v1.DataplaneControl/DeleteService"
	DataplaneControl_UpsertBackends_FullMethodName            = "/novanet.v1.DataplaneControl/UpsertBackends"
	DataplaneControl_SyncServices_FullMethodName              = "/novanet.v1.DataplaneControl/SyncServices"
	DataplaneControl_UpsertMaglevTable_FullMethodName         = "/novanet.v1.DataplaneControl/UpsertMaglevTable"
	DataplaneControl_UpsertHostPolicy_FullMethodName          = "/novanet.v1.DataplaneControl/UpsertHostPolicy"
	DataplaneControl_DeleteHostPolicy_FullMethodName          = "/novanet.v1.DataplaneControl/DeleteHostPolicy"
	DataplaneControl_SyncHostPolicies_FullMethodName          = "/novanet.v1.DataplaneControl/SyncHostPolicies"
	DataplaneControl_AttachXDP_FullMethodName                 = "/novanet.v1.DataplaneControl/AttachXDP"
	DataplaneControl_DetachXDP_FullMethodName                 = "/novanet.v1.DataplaneControl/DetachXDP"
	DataplaneControl_UpsertSockmapEndpoint_FullMethodName     = "/novanet.v1.DataplaneControl/UpsertSockmapEndpoint"
	DataplaneControl_DeleteSockmapEndpoint_FullMethodName     = "/novanet.v1.DataplaneControl/DeleteSockmapEndpoint"
	DataplaneControl_GetSockmapStats_FullMethodName           = "/novanet.v1.DataplaneControl/GetSockmapStats"
	DataplaneControl_UpsertMeshService_FullMethodName         = "/novanet.v1.DataplaneControl/UpsertMeshService"
	DataplaneControl_DeleteMeshService_FullMethodName         = "/novanet.v1.DataplaneControl/DeleteMeshService"
	DataplaneControl_ListMeshServices_FullMethodName          = "/novanet.v1.DataplaneControl/ListMeshServices"
	DataplaneControl_UpdateRateLimitConfig_FullMethodName     = "/novanet.v1.DataplaneControl/UpdateRateLimitConfig"
	DataplaneControl_GetInternalRateLimitStats_FullMethodName = "/novanet.v1.DataplaneControl/GetInternalRateLimitStats"
	DataplaneControl_GetBackendHealthStats_FullMethodName     = "/novanet.v1.DataplaneControl/GetBackendHealthStats"
	DataplaneControl_StreamFlows_FullMethodName               = "/novanet.v1.DataplaneControl/StreamFlows"
	DataplaneControl_GetDataplaneStatus_FullMethodName        = "/novanet.v1.DataplaneControl/GetDataplaneStatus"
)

// DataplaneControlClient is the client API for DataplaneControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataplaneControl is the internal API between the Go management plane
// and the Rust eBPF dataplane. The Rust dataplane runs the gRPC server,
// the Go agent is the client.
type DataplaneControlClient interface {
	// Endpoint management
	UpsertEndpoint(ctx context.Context, in *UpsertEndpointRequest, opts ...grpc.CallOption) (*UpsertEndpointResponse, error)
	DeleteEndpoint(ctx context.Context, in *DeleteEndpointRequest, opts ...grpc.CallOption) (*DeleteEndpointResponse, error)
	// Policy management
	UpsertPolicy(ctx context.Context, in *UpsertPolicyRequest, opts ...grpc.CallOption) (*UpsertPolicyResponse, error)
	DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*DeletePolicyResponse, error)
	SyncPolicies(ctx context.Context, in *SyncPoliciesRequest, opts ...grpc.CallOption) (*SyncPoliciesResponse, error)
	// Tunnel management (overlay mode)
	UpsertTunnel(ctx context.Context, in *UpsertTunnelRequest, opts ...grpc.CallOption) (*UpsertTunnelResponse, error)
	DeleteTunnel(ctx context.Context, in *DeleteTunnelRequest, opts ...grpc.CallOption) (*DeleteTunnelResponse, error)
	// Configuration
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	// TC program lifecycle
	AttachProgram(ctx context.Context, in *AttachProgramRequest, opts ...grpc.CallOption) (*AttachProgramResponse, error)
	DetachProgram(ctx context.Context, in *DetachProgramRequest, opts ...grpc.CallOption) (*DetachProgramResponse, error)
	// Egress policy management
	UpsertEgressPolicy(ctx context.Context, in *UpsertEgressPolicyRequest, opts ...grpc.CallOption) (*UpsertEgressPolicyResponse, error)
	DeleteEgressPolicy(ctx context.Context, in *DeleteEgressPolicyRequest, opts ...grpc.CallOption) (*DeleteEgressPolicyResponse, error)
	// L4 Load Balancer
	UpsertService(ctx context.Context, in *UpsertServiceRequest, opts ...grpc.CallOption) (*UpsertServiceResponse, error)
	DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*DeleteServiceResponse, error)
	UpsertBackends(ctx context.Context, in *UpsertBackendsRequest, opts ...grpc.CallOption) (*UpsertBackendsResponse, error)
	SyncServices(ctx context.Context, in *SyncServicesRequest, opts ...grpc.CallOption) (*SyncServicesResponse, error)
	UpsertMaglevTable(ctx context.Context, in *UpsertMaglevTableRequest, opts ...grpc.CallOption) (*UpsertMaglevTableResponse, error)
	// Host firewall
	UpsertHostPolicy(ctx context.Context, in *UpsertHostPolicyRequest, opts ...grpc.CallOption) (*UpsertHostPolicyResponse, error)
	DeleteHostPolicy(ctx context.Context, in *DeleteHostPolicyRequest, opts ...grpc.CallOption) (*DeleteHostPolicyResponse, error)
	SyncHostPolicies(ctx context.Context, in *SyncHostPoliciesRequest, opts ...grpc.CallOption) (*SyncHostPoliciesResponse, error)
	// XDP management
	AttachXDP(ctx context.Context, in *AttachXDPRequest, opts ...grpc.CallOption) (*AttachXDPResponse, error)
	DetachXDP(ctx context.Context, in *DetachXDPRequest, opts ...grpc.CallOption) (*DetachXDPResponse, error)
	// SOCKMAP endpoints
	UpsertSockmapEndpoint(ctx context.Context, in *UpsertSockmapEndpointRequest, opts ...grpc.CallOption) (*UpsertSockmapEndpointResponse, error)
	DeleteSockmapEndpoint(ctx context.Context, in *DeleteSockmapEndpointRequest, opts ...grpc.CallOption) (*DeleteSockmapEndpointResponse, error)
	GetSockmapStats(ctx context.Context, in *GetInternalSockmapStatsRequest, opts ...grpc.CallOption) (*GetInternalSockmapStatsResponse, error)
	// Mesh redirect
	UpsertMeshService(ctx context.Context, in *UpsertMeshServiceRequest, opts ...grpc.CallOption) (*UpsertMeshServiceResponse, error)
	DeleteMeshService(ctx context.Context, in *DeleteMeshServiceRequest, opts ...grpc.CallOption) (*DeleteMeshServiceResponse, error)
	ListMeshServices(ctx context.Context, in *ListInternalMeshServicesRequest, opts ...grpc.CallOption) (*ListInternalMeshServicesResponse, error)
	// Rate limiting
	UpdateRateLimitConfig(ctx context.Context, in *UpdateRateLimitConfigRequest, opts ...grpc.CallOption) (*UpdateRateLimitConfigResponse, error)
	GetInternalRateLimitStats(ctx context.Context, in *GetInternalRateLimitStatsRequest, opts ...grpc.CallOption) (*GetInternalRateLimitStatsResponse, error)
	// Health monitoring
	GetBackendHealthStats(ctx context.Context, in *GetBackendHealthStatsRequest, opts ...grpc.CallOption) (*GetBackendHealthStatsResponse, error)
	// Observability
	StreamFlows(ctx context.Context, in *StreamFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowEvent], error)
	GetDataplaneStatus(ctx context.Context, in *GetDataplaneStatusRequest, opts ...grpc.CallOption) (*GetDataplaneStatusResponse, error)
}

type dataplaneControlClient struct {
	cc grpc.ClientConnInterface
}

func NewDataplaneControlClient(cc grpc.ClientConnInterface) DataplaneControlClient {
	return &dataplaneControlClient{cc}
}

func (c *dataplaneControlClient) UpsertEndpoint(ctx context.Context, in *UpsertEndpointRequest, opts ...grpc.CallOption) (*UpsertEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertEndpointResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteEndpoint(ctx context.Context, in *DeleteEndpointRequest, opts ...grpc.CallOption) (*DeleteEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEndpointResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertPolicy(ctx context.Context, in *UpsertPolicyRequest, opts ...grpc.CallOption) (*UpsertPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertPolicyResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*DeletePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePolicyResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeletePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) SyncPolicies(ctx context.Context, in *SyncPoliciesRequest, opts ...grpc.CallOption) (*SyncPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncPoliciesResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_SyncPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertTunnel(ctx context.Context, in *UpsertTunnelRequest, opts ...grpc.CallOption) (*UpsertTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertTunnelResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteTunnel(ctx context.Context, in *DeleteTunnelRequest, opts ...grpc.CallOption) (*DeleteTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTunnelResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) AttachProgram(ctx context.Context, in *AttachProgramRequest, opts ...grpc.CallOption) (*AttachProgramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachProgramResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_AttachProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DetachProgram(ctx context.Context, in *DetachProgramRequest, opts ...grpc.CallOption) (*DetachProgramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachProgramResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DetachProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertEgressPolicy(ctx context.Context, in *UpsertEgressPolicyRequest, opts ...grpc.CallOption) (*UpsertEgressPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertEgressPolicyResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertEgressPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteEgressPolicy(ctx context.Context, in *DeleteEgressPolicyRequest, opts ...grpc.CallOption) (*DeleteEgressPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEgressPolicyResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteEgressPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertService(ctx context.Context, in *UpsertServiceRequest, opts ...grpc.CallOption) (*UpsertServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertServiceResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*DeleteServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteServiceResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertBackends(ctx context.Context, in *UpsertBackendsRequest, opts ...grpc.CallOption) (*UpsertBackendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertBackendsResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertBackends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) SyncServices(ctx context.Context, in *SyncServicesRequest, opts ...grpc.CallOption) (*SyncServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncServicesResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_SyncServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertMaglevTable(ctx context.Context, in *UpsertMaglevTableRequest, opts ...grpc.CallOption) (*UpsertMaglevTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertMaglevTableResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertMaglevTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertHostPolicy(ctx context.Context, in *UpsertHostPolicyRequest, opts ...grpc.CallOption) (*UpsertHostPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertHostPolicyResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertHostPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteHostPolicy(ctx context.Context, in *DeleteHostPolicyRequest, opts ...grpc.CallOption) (*DeleteHostPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHostPolicyResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteHostPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) SyncHostPolicies(ctx context.Context, in *SyncHostPoliciesRequest, opts ...grpc.CallOption) (*SyncHostPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncHostPoliciesResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_SyncHostPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) AttachXDP(ctx context.Context, in *AttachXDPRequest, opts ...grpc.CallOption) (*AttachXDPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachXDPResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_AttachXDP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DetachXDP(ctx context.Context, in *DetachXDPRequest, opts ...grpc.CallOption) (*DetachXDPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachXDPResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DetachXDP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertSockmapEndpoint(ctx context.Context, in *UpsertSockmapEndpointRequest, opts ...grpc.CallOption) (*UpsertSockmapEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertSockmapEndpointResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertSockmapEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteSockmapEndpoint(ctx context.Context, in *DeleteSockmapEndpointRequest, opts ...grpc.CallOption) (*DeleteSockmapEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSockmapEndpointResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteSockmapEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) GetSockmapStats(ctx context.Context, in *GetInternalSockmapStatsRequest, opts ...grpc.CallOption) (*GetInternalSockmapStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInternalSockmapStatsResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_GetSockmapStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpsertMeshService(ctx context.Context, in *UpsertMeshServiceRequest, opts ...grpc.CallOption) (*UpsertMeshServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertMeshServiceResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpsertMeshService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) DeleteMeshService(ctx context.Context, in *DeleteMeshServiceRequest, opts ...grpc.CallOption) (*DeleteMeshServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMeshServiceResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_DeleteMeshService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) ListMeshServices(ctx context.Context, in *ListInternalMeshServicesRequest, opts ...grpc.CallOption) (*ListInternalMeshServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInternalMeshServicesResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_ListMeshServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) UpdateRateLimitConfig(ctx context.Context, in *UpdateRateLimitConfigRequest, opts ...grpc.CallOption) (*UpdateRateLimitConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRateLimitConfigResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_UpdateRateLimitConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) GetInternalRateLimitStats(ctx context.Context, in *GetInternalRateLimitStatsRequest, opts ...grpc.CallOption) (*GetInternalRateLimitStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInternalRateLimitStatsResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_GetInternalRateLimitStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) GetBackendHealthStats(ctx context.Context, in *GetBackendHealthStatsRequest, opts ...grpc.CallOption) (*GetBackendHealthStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBackendHealthStatsResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_GetBackendHealthStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneControlClient) StreamFlows(ctx context.Context, in *StreamFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataplaneControl_ServiceDesc.Streams[0], DataplaneControl_StreamFlows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFlowsRequest, FlowEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneControl_StreamFlowsClient = grpc.ServerStreamingClient[FlowEvent]

func (c *dataplaneControlClient) GetDataplaneStatus(ctx context.Context, in *GetDataplaneStatusRequest, opts ...grpc.CallOption) (*GetDataplaneStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataplaneStatusResponse)
	err := c.cc.Invoke(ctx, DataplaneControl_GetDataplaneStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataplaneControlServer is the server API for DataplaneControl service.
// All implementations must embed UnimplementedDataplaneControlServer
// for forward compatibility.
//
// DataplaneControl is the internal API between the Go management plane
// and the Rust eBPF dataplane. The Rust dataplane runs the gRPC server,
// the Go agent is the client.
type DataplaneControlServer interface {
	// Endpoint management
	UpsertEndpoint(context.Context, *UpsertEndpointRequest) (*UpsertEndpointResponse, error)
	DeleteEndpoint(context.Context, *DeleteEndpointRequest) (*DeleteEndpointResponse, error)
	// Policy management
	UpsertPolicy(context.Context, *UpsertPolicyRequest) (*UpsertPolicyResponse, error)
	DeletePolicy(context.Context, *DeletePolicyRequest) (*DeletePolicyResponse, error)
	SyncPolicies(context.Context, *SyncPoliciesRequest) (*SyncPoliciesResponse, error)
	// Tunnel management (overlay mode)
	UpsertTunnel(context.Context, *UpsertTunnelRequest) (*UpsertTunnelResponse, error)
	DeleteTunnel(context.Context, *DeleteTunnelRequest) (*DeleteTunnelResponse, error)
	// Configuration
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	// TC program lifecycle
	AttachProgram(context.Context, *AttachProgramRequest) (*AttachProgramResponse, error)
	DetachProgram(context.Context, *DetachProgramRequest) (*DetachProgramResponse, error)
	// Egress policy management
	UpsertEgressPolicy(context.Context, *UpsertEgressPolicyRequest) (*UpsertEgressPolicyResponse, error)
	DeleteEgressPolicy(context.Context, *DeleteEgressPolicyRequest) (*DeleteEgressPolicyResponse, error)
	// L4 Load Balancer
	UpsertService(context.Context, *UpsertServiceRequest) (*UpsertServiceResponse, error)
	DeleteService(context.Context, *DeleteServiceRequest) (*DeleteServiceResponse, error)
	UpsertBackends(context.Context, *UpsertBackendsRequest) (*UpsertBackendsResponse, error)
	SyncServices(context.Context, *SyncServicesRequest) (*SyncServicesResponse, error)
	UpsertMaglevTable(context.Context, *UpsertMaglevTableRequest) (*UpsertMaglevTableResponse, error)
	// Host firewall
	UpsertHostPolicy(context.Context, *UpsertHostPolicyRequest) (*UpsertHostPolicyResponse, error)
	DeleteHostPolicy(context.Context, *DeleteHostPolicyRequest) (*DeleteHostPolicyResponse, error)
	SyncHostPolicies(context.Context, *SyncHostPoliciesRequest) (*SyncHostPoliciesResponse, error)
	// XDP management
	AttachXDP(context.Context, *AttachXDPRequest) (*AttachXDPResponse, error)
	DetachXDP(context.Context, *DetachXDPRequest) (*DetachXDPResponse, error)
	// SOCKMAP endpoints
	UpsertSockmapEndpoint(context.Context, *UpsertSockmapEndpointRequest) (*UpsertSockmapEndpointResponse, error)
	DeleteSockmapEndpoint(context.Context, *DeleteSockmapEndpointRequest) (*DeleteSockmapEndpointResponse, error)
	GetSockmapStats(context.Context, *GetInternalSockmapStatsRequest) (*GetInternalSockmapStatsResponse, error)
	// Mesh redirect
	UpsertMeshService(context.Context, *UpsertMeshServiceRequest) (*UpsertMeshServiceResponse, error)
	DeleteMeshService(context.Context, *DeleteMeshServiceRequest) (*DeleteMeshServiceResponse, error)
	ListMeshServices(context.Context, *ListInternalMeshServicesRequest) (*ListInternalMeshServicesResponse, error)
	// Rate limiting
	UpdateRateLimitConfig(context.Context, *UpdateRateLimitConfigRequest) (*UpdateRateLimitConfigResponse, error)
	GetInternalRateLimitStats(context.Context, *GetInternalRateLimitStatsRequest) (*GetInternalRateLimitStatsResponse, error)
	// Health monitoring
	GetBackendHealthStats(context.Context, *GetBackendHealthStatsRequest) (*GetBackendHealthStatsResponse, error)
	// Observability
	StreamFlows(*StreamFlowsRequest, grpc.ServerStreamingServer[FlowEvent]) error
	GetDataplaneStatus(context.Context, *GetDataplaneStatusRequest) (*GetDataplaneStatusResponse, error)
	mustEmbedUnimplementedDataplaneControlServer()
}

// UnimplementedDataplaneControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataplaneControlServer struct{}

func (UnimplementedDataplaneControlServer) UpsertEndpoint(context.Context, *UpsertEndpointRequest) (*UpsertEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertEndpoint not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteEndpoint(context.Context, *DeleteEndpointRequest) (*DeleteEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEndpoint not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertPolicy(context.Context, *UpsertPolicyRequest) (*UpsertPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertPolicy not implemented")
}
func (UnimplementedDataplaneControlServer) DeletePolicy(context.Context, *DeletePolicyRequest) (*DeletePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePolicy not implemented")
}
func (UnimplementedDataplaneControlServer) SyncPolicies(context.Context, *SyncPoliciesRequest) (*SyncPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncPolicies not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertTunnel(context.Context, *UpsertTunnelRequest) (*UpsertTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertTunnel not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteTunnel(context.Context, *DeleteTunnelRequest) (*DeleteTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTunnel not implemented")
}
func (UnimplementedDataplaneControlServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedDataplaneControlServer) AttachProgram(context.Context, *AttachProgramRequest) (*AttachProgramResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachProgram not implemented")
}
func (UnimplementedDataplaneControlServer) DetachProgram(context.Context, *DetachProgramRequest) (*DetachProgramResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachProgram not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertEgressPolicy(context.Context, *UpsertEgressPolicyRequest) (*UpsertEgressPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertEgressPolicy not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteEgressPolicy(context.Context, *DeleteEgressPolicyRequest) (*DeleteEgressPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEgressPolicy not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertService(context.Context, *UpsertServiceRequest) (*UpsertServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertService not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteService(context.Context, *DeleteServiceRequest) (*DeleteServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteService not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertBackends(context.Context, *UpsertBackendsRequest) (*UpsertBackendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertBackends not implemented")
}
func (UnimplementedDataplaneControlServer) SyncServices(context.Context, *SyncServicesRequest) (*SyncServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncServices not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertMaglevTable(context.Context, *UpsertMaglevTableRequest) (*UpsertMaglevTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertMaglevTable not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertHostPolicy(context.Context, *UpsertHostPolicyRequest) (*UpsertHostPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertHostPolicy not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteHostPolicy(context.Context, *DeleteHostPolicyRequest) (*DeleteHostPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHostPolicy not implemented")
}
func (UnimplementedDataplaneControlServer) SyncHostPolicies(context.Context, *SyncHostPoliciesRequest) (*SyncHostPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncHostPolicies not implemented")
}
func (UnimplementedDataplaneControlServer) AttachXDP(context.Context, *AttachXDPRequest) (*AttachXDPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachXDP not implemented")
}
func (UnimplementedDataplaneControlServer) DetachXDP(context.Context, *DetachXDPRequest) (*DetachXDPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachXDP not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertSockmapEndpoint(context.Context, *UpsertSockmapEndpointRequest) (*UpsertSockmapEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertSockmapEndpoint not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteSockmapEndpoint(context.Context, *DeleteSockmapEndpointRequest) (*DeleteSockmapEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSockmapEndpoint not implemented")
}
func (UnimplementedDataplaneControlServer) GetSockmapStats(context.Context, *GetInternalSockmapStatsRequest) (*GetInternalSockmapStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSockmapStats not implemented")
}
func (UnimplementedDataplaneControlServer) UpsertMeshService(context.Context, *UpsertMeshServiceRequest) (*UpsertMeshServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertMeshService not implemented")
}
func (UnimplementedDataplaneControlServer) DeleteMeshService(context.Context, *DeleteMeshServiceRequest) (*DeleteMeshServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMeshService not implemented")
}
func (UnimplementedDataplaneControlServer) ListMeshServices(context.Context, *ListInternalMeshServicesRequest) (*ListInternalMeshServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMeshServices not implemented")
}
func (UnimplementedDataplaneControlServer) UpdateRateLimitConfig(context.Context, *UpdateRateLimitConfigRequest) (*UpdateRateLimitConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRateLimitConfig not implemented")
}
func (UnimplementedDataplaneControlServer) GetInternalRateLimitStats(context.Context, *GetInternalRateLimitStatsRequest) (*GetInternalRateLimitStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInternalRateLimitStats not implemented")
}
func (UnimplementedDataplaneControlServer) GetBackendHealthStats(context.Context, *GetBackendHealthStatsRequest) (*GetBackendHealthStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBackendHealthStats not implemented")
}
func (UnimplementedDataplaneControlServer) StreamFlows(*StreamFlowsRequest, grpc.ServerStreamingServer[FlowEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamFlows not implemented")
}
func (UnimplementedDataplaneControlServer) GetDataplaneStatus(context.Context, *GetDataplaneStatusRequest) (*GetDataplaneStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDataplaneStatus not implemented")
}
func (UnimplementedDataplaneControlServer) mustEmbedUnimplementedDataplaneControlServer() {}
func (UnimplementedDataplaneControlServer) testEmbeddedByValue()                          {}

// UnsafeDataplaneControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataplaneControlServer will
// result in compilation errors.
type UnsafeDataplaneControlServer interface {
	mustEmbedUnimplementedDataplaneControlServer()
}

func RegisterDataplaneControlServer(s grpc.ServiceRegistrar, srv DataplaneControlServer) {
	// If the following call panics, it indicates UnimplementedDataplaneControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataplaneControl_ServiceDesc, srv)
}

func _DataplaneControl_UpsertEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertEndpoint(ctx, req.(*UpsertEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteEndpoint(ctx, req.(*DeleteEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertPolicy(ctx, req.(*UpsertPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeletePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeletePolicy(ctx, req.(*DeletePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_SyncPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).SyncPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_SyncPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).SyncPolicies(ctx, req.(*SyncPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertTunnel(ctx, req.(*UpsertTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteTunnel(ctx, req.(*DeleteTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_AttachProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).AttachProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_AttachProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).AttachProgram(ctx, req.(*AttachProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DetachProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DetachProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DetachProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DetachProgram(ctx, req.(*DetachProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertEgressPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertEgressPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertEgressPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertEgressPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertEgressPolicy(ctx, req.(*UpsertEgressPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteEgressPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEgressPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteEgressPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteEgressPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteEgressPolicy(ctx, req.(*DeleteEgressPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertService(ctx, req.(*UpsertServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteService(ctx, req.(*DeleteServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertBackends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertBackendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertBackends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertBackends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertBackends(ctx, req.(*UpsertBackendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_SyncServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).SyncServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_SyncServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).SyncServices(ctx, req.(*SyncServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertMaglevTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertMaglevTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertMaglevTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertMaglevTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertMaglevTable(ctx, req.(*UpsertMaglevTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertHostPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertHostPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertHostPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertHostPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertHostPolicy(ctx, req.(*UpsertHostPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteHostPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHostPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteHostPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteHostPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteHostPolicy(ctx, req.(*DeleteHostPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_SyncHostPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncHostPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).SyncHostPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_SyncHostPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).SyncHostPolicies(ctx, req.(*SyncHostPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_AttachXDP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachXDPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).AttachXDP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_AttachXDP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).AttachXDP(ctx, req.(*AttachXDPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DetachXDP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachXDPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DetachXDP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DetachXDP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DetachXDP(ctx, req.(*DetachXDPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertSockmapEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertSockmapEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertSockmapEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertSockmapEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertSockmapEndpoint(ctx, req.(*UpsertSockmapEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteSockmapEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSockmapEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteSockmapEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteSockmapEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteSockmapEndpoint(ctx, req.(*DeleteSockmapEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_GetSockmapStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInternalSockmapStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).GetSockmapStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_GetSockmapStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).GetSockmapStats(ctx, req.(*GetInternalSockmapStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpsertMeshService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertMeshServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpsertMeshService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpsertMeshService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpsertMeshService(ctx, req.(*UpsertMeshServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_DeleteMeshService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMeshServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).DeleteMeshService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_DeleteMeshService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).DeleteMeshService(ctx, req.(*DeleteMeshServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_ListMeshServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInternalMeshServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).ListMeshServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_ListMeshServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).ListMeshServices(ctx, req.(*ListInternalMeshServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_UpdateRateLimitConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRateLimitConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).UpdateRateLimitConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_UpdateRateLimitConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).UpdateRateLimitConfig(ctx, req.(*UpdateRateLimitConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_GetInternalRateLimitStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInternalRateLimitStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).GetInternalRateLimitStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_GetInternalRateLimitStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).GetInternalRateLimitStats(ctx, req.(*GetInternalRateLimitStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_GetBackendHealthStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackendHealthStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).GetBackendHealthStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_GetBackendHealthStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).GetBackendHealthStats(ctx, req.(*GetBackendHealthStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneControl_StreamFlows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamFlowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataplaneControlServer).StreamFlows(m, &grpc.GenericServerStream[StreamFlowsRequest, FlowEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataplaneControl_StreamFlowsServer = grpc.ServerStreamingServer[FlowEvent]

func _DataplaneControl_GetDataplaneStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataplaneStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneControlServer).GetDataplaneStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneControl_GetDataplaneStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneControlServer).GetDataplaneStatus(ctx, req.(*GetDataplaneStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataplaneControl_ServiceDesc is the grpc.ServiceDesc for DataplaneControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataplaneControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novanet.v1.DataplaneControl",
	HandlerType: (*DataplaneControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertEndpoint",
			Handler:    _DataplaneControl_UpsertEndpoint_Handler,
		},
		{
			MethodName: "DeleteEndpoint",
			Handler:    _DataplaneControl_DeleteEndpoint_Handler,
		},
		{
			MethodName: "UpsertPolicy",
			Handler:    _DataplaneControl_UpsertPolicy_Handler,
		},
		{
			MethodName: "DeletePolicy",
			Handler:    _DataplaneControl_DeletePolicy_Handler,
		},
		{
			MethodName: "SyncPolicies",
			Handler:    _DataplaneControl_SyncPolicies_Handler,
		},
		{
			MethodName: "UpsertTunnel",
			Handler:    _DataplaneControl_UpsertTunnel_Handler,
		},
		{
			MethodName: "DeleteTunnel",
			Handler:    _DataplaneControl_DeleteTunnel_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _DataplaneControl_UpdateConfig_Handler,
		},
		{
			MethodName: "AttachProgram",
			Handler:    _DataplaneControl_AttachProgram_Handler,
		},
		{
			MethodName: "DetachProgram",
			Handler:    _DataplaneControl_DetachProgram_Handler,
		},
		{
			MethodName: "UpsertEgressPolicy",
			Handler:    _DataplaneControl_UpsertEgressPolicy_Handler,
		},
		{
			MethodName: "DeleteEgressPolicy",
			Handler:    _DataplaneControl_DeleteEgressPolicy_Handler,
		},
		{
			MethodName: "UpsertService",
			Handler:    _DataplaneControl_UpsertService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _DataplaneControl_DeleteService_Handler,
		},
		{
			MethodName: "UpsertBackends",
			Handler:    _DataplaneControl_UpsertBackends_Handler,
		},
		{
			MethodName: "SyncServices",
			Handler:    _DataplaneControl_SyncServices_Handler,
		},
		{
			MethodName: "UpsertMaglevTable",
			Handler:    _DataplaneControl_UpsertMaglevTable_Handler,
		},
		{
			MethodName: "UpsertHostPolicy",
			Handler:    _DataplaneControl_UpsertHostPolicy_Handler,
		},
		{
			MethodName: "DeleteHostPolicy",
			Handler:    _DataplaneControl_DeleteHostPolicy_Handler,
		},
		{
			MethodName: "SyncHostPolicies",
			Handler:    _DataplaneControl_SyncHostPolicies_Handler,
		},
		{
			MethodName: "AttachXDP",
			Handler:    _DataplaneControl_AttachXDP_Handler,
		},
		{
			MethodName: "DetachXDP",
			Handler:    _DataplaneControl_DetachXDP_Handler,
		},
		{
			MethodName: "UpsertSockmapEndpoint",
			Handler:    _DataplaneControl_UpsertSockmapEndpoint_Handler,
		},
		{
			MethodName: "DeleteSockmapEndpoint",
			Handler:    _DataplaneControl_DeleteSockmapEndpoint_Handler,
		},
		{
			MethodName: "GetSockmapStats",
			Handler:    _DataplaneControl_GetSockmapStats_Handler,
		},
		{
			MethodName: "UpsertMeshService",
			Handler:    _DataplaneControl_UpsertMeshService_Handler,
		},
		{
			MethodName: "DeleteMeshService",
			Handler:    _DataplaneControl_DeleteMeshService_Handler,
		},
		{
			MethodName: "ListMeshServices",
			Handler:    _DataplaneControl_ListMeshServices_Handler,
		},
		{
			MethodName: "UpdateRateLimitConfig",
			Handler:    _DataplaneControl_UpdateRateLimitConfig_Handler,
		},
		{
			MethodName: "GetInternalRateLimitStats",
			Handler:    _DataplaneControl_GetInternalRateLimitStats_Handler,
		},
		{
			MethodName: "GetBackendHealthStats",
			Handler:    _DataplaneControl_GetBackendHealthStats_Handler,
		},
		{
			MethodName: "GetDataplaneStatus",
			Handler:    _DataplaneControl_GetDataplaneStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFlows",
			Handler:       _DataplaneControl_StreamFlows_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/novanet.proto",
}

const (
	AgentControl_AddPod_FullMethodName                  = "/novanet.v1.AgentControl/AddPod"
	AgentControl_DelPod_FullMethodName                  = "/novanet.v1.AgentControl/DelPod"
	AgentControl_GetAgentStatus_FullMethodName          = "/novanet.v1.AgentControl/GetAgentStatus"
	AgentControl_StreamAgentFlows_FullMethodName        = "/novanet.v1.AgentControl/StreamAgentFlows"
	AgentControl_ListPolicies_FullMethodName            = "/novanet.v1.AgentControl/ListPolicies"
	AgentControl_ListIdentities_FullMethodName          = "/novanet.v1.AgentControl/ListIdentities"
	AgentControl_ListTunnels_FullMethodName             = "/novanet.v1.AgentControl/ListTunnels"
	AgentControl_ListEgressPolicies_FullMethodName      = "/novanet.v1.AgentControl/ListEgressPolicies"
	AgentControl_ListServices_FullMethodName            = "/novanet.v1.AgentControl/ListServices"
	AgentControl_GetRoutingPeers_FullMethodName         = "/novanet.v1.AgentControl/GetRoutingPeers"
	AgentControl_GetRoutingPrefixes_FullMethodName      = "/novanet.v1.AgentControl/GetRoutingPrefixes"
	AgentControl_GetRoutingBFDSessions_FullMethodName   = "/novanet.v1.AgentControl/GetRoutingBFDSessions"
	AgentControl_GetRoutingOSPFNeighbors_FullMethodName = "/novanet.v1.AgentControl/GetRoutingOSPFNeighbors"
	AgentControl_StreamRoutingEvents_FullMethodName     = "/novanet.v1.AgentControl/StreamRoutingEvents"
)

// AgentControlClient is the client API for AgentControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentControl is the API exposed by the Go agent for CNI binary
// and CLI tool connections.
type AgentControlClient interface {
	// CNI operations
	AddPod(ctx context.Context, in *AddPodRequest, opts ...grpc.CallOption) (*AddPodResponse, error)
	DelPod(ctx context.Context, in *DelPodRequest, opts ...grpc.CallOption) (*DelPodResponse, error)
	// Status
	GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*GetAgentStatusResponse, error)
	// Flow streaming (proxied from dataplane)
	StreamAgentFlows(ctx context.Context, in *StreamAgentFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowEvent], error)
	// List RPCs (CLI)
	ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error)
	ListIdentities(ctx context.Context, in *ListIdentitiesRequest, opts ...grpc.CallOption) (*ListIdentitiesResponse, error)
	ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error)
	ListEgressPolicies(ctx context.Context, in *ListEgressPoliciesRequest, opts ...grpc.CallOption) (*ListEgressPoliciesResponse, error)
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// Routing RPCs (native mode — queries FRR state via routing manager)
	GetRoutingPeers(ctx context.Context, in *GetRoutingPeersRequest, opts ...grpc.CallOption) (*GetRoutingPeersResponse, error)
	GetRoutingPrefixes(ctx context.Context, in *GetRoutingPrefixesRequest, opts ...grpc.CallOption) (*GetRoutingPrefixesResponse, error)
	GetRoutingBFDSessions(ctx context.Context, in *GetRoutingBFDSessionsRequest, opts ...grpc.CallOption) (*GetRoutingBFDSessionsResponse, error)
	GetRoutingOSPFNeighbors(ctx context.Context, in *GetRoutingOSPFNeighborsRequest, opts ...grpc.CallOption) (*GetRoutingOSPFNeighborsResponse, error)
	StreamRoutingEvents(ctx context.Context, in *StreamRoutingEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoutingEvent], error)
}

type agentControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlClient(cc grpc.ClientConnInterface) AgentControlClient {
	return &agentControlClient{cc}
}

func (c *agentControlClient) AddPod(ctx context.Context, in *AddPodRequest, opts ...grpc.CallOption) (*AddPodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPodResponse)
	err := c.cc.Invoke(ctx, AgentControl_AddPod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) DelPod(ctx context.Context, in *DelPodRequest, opts ...grpc.CallOption) (*DelPodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelPodResponse)
	err := c.cc.Invoke(ctx, AgentControl_DelPod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetAgentStatus(ctx context.Context, in *GetAgentStatusRequest, opts ...grpc.CallOption) (*GetAgentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentStatusResponse)
	err := c.cc.Invoke(ctx, AgentControl_GetAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) StreamAgentFlows(ctx context.Context, in *StreamAgentFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControl_ServiceDesc.Streams[0], AgentControl_StreamAgentFlows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAgentFlowsRequest, FlowEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_StreamAgentFlowsClient = grpc.ServerStreamingClient[FlowEvent]

func (c *agentControlClient) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoliciesResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ListIdentities(ctx context.Context, in *ListIdentitiesRequest, opts ...grpc.CallOption) (*ListIdentitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIdentitiesResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTunnelsResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListTunnels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ListEgressPolicies(ctx context.Context, in *ListEgressPoliciesRequest, opts ...grpc.CallOption) (*ListEgressPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEgressPoliciesResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListEgressPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetRoutingPeers(ctx context.Context, in *GetRoutingPeersRequest, opts ...grpc.CallOption) (*GetRoutingPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingPeersResponse)
	err := c.cc.Invoke(ctx, AgentControl_GetRoutingPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetRoutingPrefixes(ctx context.Context, in *GetRoutingPrefixesRequest, opts ...grpc.CallOption) (*GetRoutingPrefixesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingPrefixesResponse)
	err := c.cc.Invoke(ctx, AgentControl_GetRoutingPrefixes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetRoutingBFDSessions(ctx context.Context, in *GetRoutingBFDSessionsRequest, opts ...grpc.CallOption) (*GetRoutingBFDSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingBFDSessionsResponse)
	err := c.cc.Invoke(ctx, AgentControl_GetRoutingBFDSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetRoutingOSPFNeighbors(ctx context.Context, in *GetRoutingOSPFNeighborsRequest, opts ...grpc.CallOption) (*GetRoutingOSPFNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingOSPFNeighborsResponse)
	err := c.cc.Invoke(ctx, AgentControl_GetRoutingOSPFNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) StreamRoutingEvents(ctx context.Context, in *StreamRoutingEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoutingEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControl_ServiceDesc.Streams[1], AgentControl_StreamRoutingEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRoutingEventsRequest, RoutingEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_StreamRoutingEventsClient = grpc.ServerStreamingClient[RoutingEvent]

// AgentControlServer is the server API for AgentControl service.
// All implementations must embed UnimplementedAgentControlServer
// for forward compatibility.
//
// AgentControl is the API exposed by the Go agent for CNI binary
// and CLI tool connections.
type AgentControlServer interface {
	// CNI operations
	AddPod(context.Context, *AddPodRequest) (*AddPodResponse, error)
	DelPod(context.Context, *DelPodRequest) (*DelPodResponse, error)
	// Status
	GetAgentStatus(context.Context, *GetAgentStatusRequest) (*GetAgentStatusResponse, error)
	// Flow streaming (proxied from dataplane)
	StreamAgentFlows(*StreamAgentFlowsRequest, grpc.ServerStreamingServer[FlowEvent]) error
	// List RPCs (CLI)
	ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error)
	ListIdentities(context.Context, *ListIdentitiesRequest) (*ListIdentitiesResponse, error)
	ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error)
	ListEgressPolicies(context.Context, *ListEgressPoliciesRequest) (*ListEgressPoliciesResponse, error)
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// Routing RPCs (native mode — queries FRR state via routing manager)
	GetRoutingPeers(context.Context, *GetRoutingPeersRequest) (*GetRoutingPeersResponse, error)
	GetRoutingPrefixes(context.Context, *GetRoutingPrefixesRequest) (*GetRoutingPrefixesResponse, error)
	GetRoutingBFDSessions(context.Context, *GetRoutingBFDSessionsRequest) (*GetRoutingBFDSessionsResponse, error)
	GetRoutingOSPFNeighbors(context.Context, *GetRoutingOSPFNeighborsRequest) (*GetRoutingOSPFNeighborsResponse, error)
	StreamRoutingEvents(*StreamRoutingEventsRequest, grpc.ServerStreamingServer[RoutingEvent]) error
	mustEmbedUnimplementedAgentControlServer()
}

// UnimplementedAgentControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlServer struct{}

func (UnimplementedAgentControlServer) AddPod(context.Context, *AddPodRequest) (*AddPodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPod not implemented")
}
func (UnimplementedAgentControlServer) DelPod(context.Context, *DelPodRequest) (*DelPodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelPod not implemented")
}
func (UnimplementedAgentControlServer) GetAgentStatus(context.Context, *GetAgentStatusRequest) (*GetAgentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentStatus not implemented")
}
func (UnimplementedAgentControlServer) StreamAgentFlows(*StreamAgentFlowsRequest, grpc.ServerStreamingServer[FlowEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamAgentFlows not implemented")
}
func (UnimplementedAgentControlServer) ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedAgentControlServer) ListIdentities(context.Context, *ListIdentitiesRequest) (*ListIdentitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIdentities not implemented")
}
func (UnimplementedAgentControlServer) ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTunnels not implemented")
}
func (UnimplementedAgentControlServer) ListEgressPolicies(context.Context, *ListEgressPoliciesRequest) (*ListEgressPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEgressPolicies not implemented")
}
func (UnimplementedAgentControlServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedAgentControlServer) GetRoutingPeers(context.Context, *GetRoutingPeersRequest) (*GetRoutingPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutingPeers not implemented")
}
func (UnimplementedAgentControlServer) GetRoutingPrefixes(context.Context, *GetRoutingPrefixesRequest) (*GetRoutingPrefixesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutingPrefixes not implemented")
}
func (UnimplementedAgentControlServer) GetRoutingBFDSessions(context.Context, *GetRoutingBFDSessionsRequest) (*GetRoutingBFDSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutingBFDSessions not implemented")
}
func (UnimplementedAgentControlServer) GetRoutingOSPFNeighbors(context.Context, *GetRoutingOSPFNeighborsRequest) (*GetRoutingOSPFNeighborsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutingOSPFNeighbors not implemented")
}
func (UnimplementedAgentControlServer) StreamRoutingEvents(*StreamRoutingEventsRequest, grpc.ServerStreamingServer[RoutingEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamRoutingEvents not implemented")
}
func (UnimplementedAgentControlServer) mustEmbedUnimplementedAgentControlServer() {}
func (UnimplementedAgentControlServer) testEmbeddedByValue()                      {}

// UnsafeAgentControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlServer will
// result in compilation errors.
type UnsafeAgentControlServer interface {
	mustEmbedUnimplementedAgentControlServer()
}

func RegisterAgentControlServer(s grpc.ServiceRegistrar, srv AgentControlServer) {
	// If the following call panics, it indicates UnimplementedAgentControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControl_ServiceDesc, srv)
}

func _AgentControl_AddPod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).AddPod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_AddPod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).AddPod(ctx, req.(*AddPodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_DelPod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelPodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).DelPod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_DelPod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).DelPod(ctx, req.(*DelPodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetAgentStatus(ctx, req.(*GetAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_StreamAgentFlows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAgentFlowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentControlServer).StreamAgentFlows(m, &grpc.GenericServerStream[StreamAgentFlowsRequest, FlowEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_StreamAgentFlowsServer = grpc.ServerStreamingServer[FlowEvent]

func _AgentControl_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListPolicies(ctx, req.(*ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ListIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListIdentities(ctx, req.(*ListIdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ListTunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTunnelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListTunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListTunnels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListTunnels(ctx, req.(*ListTunnelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ListEgressPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEgressPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListEgressPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListEgressPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListEgressPolicies(ctx, req.(*ListEgressPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetRoutingPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetRoutingPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetRoutingPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetRoutingPeers(ctx, req.(*GetRoutingPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetRoutingPrefixes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingPrefixesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetRoutingPrefixes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetRoutingPrefixes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetRoutingPrefixes(ctx, req.(*GetRoutingPrefixesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetRoutingBFDSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingBFDSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetRoutingBFDSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetRoutingBFDSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetRoutingBFDSessions(ctx, req.(*GetRoutingBFDSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetRoutingOSPFNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingOSPFNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetRoutingOSPFNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetRoutingOSPFNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetRoutingOSPFNeighbors(ctx, req.(*GetRoutingOSPFNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_StreamRoutingEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRoutingEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentControlServer).StreamRoutingEvents(m, &grpc.GenericServerStream[StreamRoutingEventsRequest, RoutingEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_StreamRoutingEventsServer = grpc.ServerStreamingServer[RoutingEvent]

// AgentControl_ServiceDesc is the grpc.ServiceDesc for AgentControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novanet.v1.AgentControl",
	HandlerType: (*AgentControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPod",
			Handler:    _AgentControl_AddPod_Handler,
		},
		{
			MethodName: "DelPod",
			Handler:    _AgentControl_DelPod_Handler,
		},
		{
			MethodName: "GetAgentStatus",
			Handler:    _AgentControl_GetAgentStatus_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _AgentControl_ListPolicies_Handler,
		},
		{
			MethodName: "ListIdentities",
			Handler:    _AgentControl_ListIdentities_Handler,
		},
		{
			MethodName: "ListTunnels",
			Handler:    _AgentControl_ListTunnels_Handler,
		},
		{
			MethodName: "ListEgressPolicies",
			Handler:    _AgentControl_ListEgressPolicies_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _AgentControl_ListServices_Handler,
		},
		{
			MethodName: "GetRoutingPeers",
			Handler:    _AgentControl_GetRoutingPeers_Handler,
		},
		{
			MethodName: "GetRoutingPrefixes",
			Handler:    _AgentControl_GetRoutingPrefixes_Handler,
		},
		{
			MethodName: "GetRoutingBFDSessions",
			Handler:    _AgentControl_GetRoutingBFDSessions_Handler,
		},
		{
			MethodName: "GetRoutingOSPFNeighbors",
			Handler:    _AgentControl_GetRoutingOSPFNeighbors_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAgentFlows",
			Handler:       _AgentControl_StreamAgentFlows_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamRoutingEvents",
			Handler:       _AgentControl_StreamRoutingEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/novanet.proto",
}
