apiVersion: v2
name: novanet
description: NovaNet eBPF-based Kubernetes CNI
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.28.0"
home: https://github.com/azrtydxb/novanet
sources:
  - https://github.com/azrtydxb/novanet
maintainers:
  - name: Pascal Watteel
    url: https://github.com/azrtydxb
keywords:
  - cni
  - ebpf
  - networking
  - kubernetes
